### ISSUE TITLE
Inconsistent width_of with ascii character

### ISSUE THREAD

**Issue by vanboom** [prawnpdf/prawn#1006]
width_of is returning a double width size for an inline-list bullet, ascii \u2022 character. 

pdf.width_of "1." returns 7.505999999
pdf.width_of "•" returns 15.01199999

**Comment by pointlessone** [comment]
The widths depend on the font you use. It is completely possible that the font provides unexpected metrics.

For example, here's what Prawn gives me for default font ("Time New Roman"):
```ruby
Prawn::Document.new do |pdf|
  puts pdf.width_of("1.") # => 10.008000000000001
  puts pdf.width_of("\u2022") # => 4.2
end
```

You can use any font-editing software to inspect your font. For instance, FontForge is free and while it looks terrible it can help you in this task.

---

I will close this issue now. Feel free to reopen if you discover that it's Prawns fault. In that case please submit relevant font metrics or the font file itself if possible.
