### ISSUE TITLE
Error loading prawn/table

### ISSUE THREAD

**Issue by mcris-roberto** [prawnpdf/prawn#1012]
Hi,

This might be environment-related issue, but Im encountering the following errors when using the prawn/table

`irb(main):002:0> require 'prawn'
=> true
irb(main):003:0> require 'prawn/table'
NameError: uninitialized constant Prawn::Configurable
	from /Users/xxxx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/prawn-layout-0.8.4/lib/prawn/table.rb:79:in `<class:Table>'
	from /Users/xxxx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/prawn-layout-0.8.4/lib/prawn/table.rb:77:in `<module:Prawn>'
	from /Users/xxxx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/prawn-layout-0.8.4/lib/prawn/table.rb:11:in `<top (required)>'
	from /Users/xxxx/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/xxxx/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from (irb):3
	from /Users/xxxx/.rbenv/versions/2.3.1/bin/irb:11:in `<main>'`

Im using 
`irb(main):007:0> Prawn::VERSION
=> "2.2.1"`

and 

`irb(main):008:0> RUBY_VERSION
=> "2.3.1"`

and on MACOS Sierra

Thank you very much in advance

**Comment by pointlessone** [comment]
Hello Maricris,

`prawn-layout` is a very old gem. It's most likely not compatible with the latest Prawn gems. If you need a table try your luck with `prawn-table` gem.

---

I will close this issue now as it's related to an unsupported code. Feel free to reopen if you have anything to add to the discussion.
