### ISSUE TITLE
Font information missing in UnknownFont error message

### ISSUE THREAD

**Issue by mojavelinux** [prawnpdf/prawn#1022]
When a font cannot be found, users often see the following error message:

```
 is not a known font.
```

This happens when a font family + font style font combination is not found in the font registry. Prawn falls back to loading an AFM font. However, in this case, the name argument is always nil and the error message reports a blank font. All the font information is sitting in the options argument.

In afm.rb, I prose changing:

```ruby
def initialize(document, name, options = {}) #:nodoc:

  unless BUILT_INS.include?(name)
    raise Prawn::Errors::UnknownFont, "#{name} is not a known font."
  end
```

to

```ruby
def initialize(document, name, options = {}) #:nodoc:
  name ||= options[:family]
  unless BUILT_INS.include?(name)
    raise Prawn::Errors::UnknownFont, "#{[name, options[:style]].compact * ':'} is not a known font."
  end
```

That way, the error message will be:

```
Noto Serif:bold-italic is not a known font.
```

The message will be consistent whether it's the family or the family + style that can't be matched.

**Comment by settermjd** [comment]
Please do! I just encountered this error, changed the file with your change, and now I know what the problem is.

**Comment by brandoncc** [comment]
This just solved my problem as well, please add it to the repo!

**Comment by mojavelinux** [comment]
Added!
