### ISSUE TITLE
Warnings Prawn - PDF Core

### ISSUE THREAD

**Issue by Zyphrax** [prawnpdf/prawn#1024]
The new version of PDF core (0.7.0) is causing warnings in our production environment:

> vendor/bundle/ruby/2.3.0/gems/pdf-core-0.7.0/lib/pdf/core/text.rb:12: warning: already initialized constant PDF::Core::Text::VALID_OPTIONS
> vendor/bundle/ruby/2.3.0/gems/pdf-core-0.7.0/lib/pdf/core/text.rb:12: warning: previous definition of VALID_OPTIONS was here
> vendor/bundle/ruby/2.3.0/gems/pdf-core-0.7.0/lib/pdf/core/text.rb:13: warning: already initialized constant PDF::Core::Text::MODES
> vendor/bundle/ruby/2.3.0/gems/pdf-core-0.7.0/lib/pdf/core/text.rb:13: warning: previous definition of MODES was here

For more details see: https://github.com/prawnpdf/pdf-core/issues/30#issuecomment-299492785

@rrosenblum suggests that the way to fix this is to change the way that Prawn requires PDF Core.

**Comment by AnwarShah** [comment]
Any progress on this?

**Comment by rrosenblum** [comment]
I am not sure what the progress is. I can revive the pull request that I created a few months ago.

**Comment by Zyphrax** [comment]
Thanks @rrosenblum 

It would be great if the pull request could be processed.
The warnings are really annoying.

**Comment by shevegen** [comment]
Warnings that are not important should ideally not be shown.

In the example above, this tends to happen when there are wrong or flawed require calls being processed. Ideally these constants should be required only once but it appears that some code requires it more than once. I do not know require_relative well enough to comment on it, but in my own ruby code when I use requires, above warnings only happen when I require the .rb files incorrectly, often in improper order.

If it helps anyone else, I usually start with important constant definitions first, in a file that is usually, aptly called, constants.rb :D

**Comment by pointlessone** [comment]
> Warnings that are not important should ideally not be shown.

I wholeheartedly agree.

Though, I shall repeat myself. Again. This is not a problem with Prawn. It's a result of a pathological environment.

**Comment by rrosenblum** [comment]
> Though, I shall repeat myself. Again. This is not a problem with Prawn. It's a result of a pathological environment.

Whether this is an issue with Prawn or not, it is something that can be fixed in Prawn.

**Comment by pointlessone** [comment]
Likewise it can be fixed elsewhere.

**Comment by Zyphrax** [comment]
Thanks!

Could you please release a new version of Prawn PDF?
It has been a while since the last release, would be great to have this fix in.

**Comment by pointlessone** [comment]
@Zyphrax Have you tried master yet? Does it fix this issue?

**Comment by Zyphrax** [comment]
@pointlessone Yes, the fix works great!

I currently have this in my Gemfile:
```
gem 'prawn', :git => 'https://github.com/prawnpdf/prawn.git', ref: '9250c8675342872603332784f77263fcb1cf72a2'
```

Probably quite a lot of people that are using Capistrano or a symbolic link for some other reason still get the warnings because they aren't using the master branch.

**Comment by Zyphrax** [comment]
@pointlessone Would a release be possible at this time? Anything I can do to help?

**Comment by pointlessone** [comment]
You're invited to participate in the further discussion: #1181.
