### ISSUE TITLE
Prawn Pdf does not work on Mobile

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [prawnpdf/prawn#1025]
Hello,

Thanks a lot for your help. I have a Web App available for both mobile and desktop. You can test this scenario by following the instructions on the bottom.

When I use the app on desktop version I can open the pdf, when I test the app on mobile with chrome responsive developer tools on a Samsung Galaxy, the pdf does not render.

Basically what happens is that the controller on mobile skips the `format.pdf do` statement for some reasons...

This is my show action:

```
  def show
    @campaign = Campaign.find(params[:campaign_id]) if params[:campaign_id].present?
    @ads = @run.ads
    respond_to do |format|
      format.html
      binding.pry
      format.pdf do
        pdf = RunPdf.new(@run, @ads)
        send_data pdf.render, filename: "Print Order N.#{@run.id}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
    @run.update(:status => "to distribute")
    flash[:warning_run] = "Now remember to check the Print Order as completed after giving away all the fliers with the icon"
  end
```
This is my link

`<%= link_to campaign_run_path(run.campaign, run, format: "pdf"), {class: "btn btn-primary", 'rel' => 'tooltip', 'data-placement' => 'top', 'title'=>"Open Pdf File"} do %><i class="fa fa-download" aria-hidden="true"></i><% end %>   
`
This is the `get "/campaigns/8/runs/33.pdf"` action from my server log on desktop:
```
Started GET "/campaigns/8/runs/33.pdf" for 127.0.0.1 at 2017-05-16 11:58:02 +0200
Processing by RunsController#show as PDF
  Parameters: {"campaign_id"=>"8", "id"=>"33"}
.....
  CACHE (0.0ms)  SELECT  "companies".* FROM "companies" WHERE "companies"."id" = $1 LIMIT $2  [["id", 14], ["LIMIT", 1]]
  Rendering text template
  Rendered text template (0.0ms)
Sent data Print Order N.33.pdf (0.7ms)
   (0.1ms)  BEGIN
   (0.1ms)  COMMIT
Completed 200 OK in 7870ms (Views: 0.6ms | ActiveRecord: 2.7ms)
```
This is the short version of my server log, I do not save to the db so I do not commit. Still it is just skipping that `format.pdf` in the controller and I do not know why.
 ```
Started GET "/campaigns/8/runs/33.pdf" for 127.0.0.1 at 2017-05-16 12:00:24 +0200
Processing by RunsController#show as PDF
  Parameters: {"campaign_id"=>"8", "id"=>"33"}
  Run Load (0.6ms)  SELECT  "runs".* FROM "runs" WHERE "runs"."id" = $1 LIMIT $2  [["id", 33], ["LIMIT", 1]]
...
CACHE (0.0ms)  SELECT  "companies".* FROM "companies" WHERE "companies"."id" = $1 LIMIT $2  [["id", 14], ["LIMIT", 1]]
  Rendering text template
  Rendered text template (0.0ms)
Sent data Print Order N.33.pdf (0.5ms)
   (0.1ms)  BEGIN
   (0.1ms)  COMMIT
Completed 200 OK in 18418ms (Views: 0.4ms | ActiveRecord: 325.4ms)

```

You can test it by signing up at 
https://growstartups.xyz/users/sign_up
And logging in at 
https://growstartups.xyz/users/sign_in

To recreate the problem you will have to, after signing up, create a company, a campaign, a print order and then trying to open the print order by clicking on the download Icon.
It works with Desktop, but with chrome responsive view for the Samsung Galaxy does not work.

Thanks a lot for your help
Best Regards
Fabrizio Bertoglio

**Comment by pointlessone** [comment]
Hi Fabrizio,

It looks like this is not a Prawn issue. It appears the browser requests wrong content type from your app.

**Comment by fabriziobertoglio1987** [comment]
You are right. The problem is connected to chrome desktop developer toolbars tolls when using the responsive view for mobile. On mobile I do not have this problem, the pdf is working on mobile.

I submitted a bug to the chrome developers and I gave them this links..

Thanks a lot for solving the issue

Fabrizio

**Comment by pointlessone** [comment]
Glad I could help you. I will close this issue now. Feel free to reopen if it turns out to be a Prawn issue.
