### ISSUE TITLE
Documentation for link_annotation? 

### ISSUE THREAD

**Issue by totic** [prawnpdf/prawn#1030]
What options does link_annotation take? I keep seeing in the examples

   :Border => [0,0,0]

But I don't see any documentation for what is it for?
Also the rectangle that you have to pass in there is no documentation what order are the points in.

Thanks

**Comment by jdraths** [comment]
`link_annotation` comes from PDF::Core via the [pdf-core gem]((https://github.com/prawnpdf/pdf-core).
Here is the documentation you are looking for: [link_annotation](https://github.com/prawnpdf/pdf-core/blob/1f0916f025d59e4e0aa31ef93f185686c80eb0bc/lib/pdf/core/annotations.rb#L34)

**Comment by gettalong** [comment]
@totic Is this issue resolved for you?

**Comment by totic** [comment]
@gettalong Nope, issue resolved! , thanks!
