### ISSUE TITLE
Highligt of formatted_text with new lines in it 

### ISSUE THREAD

**Issue by ViktorKopychko** [prawnpdf/prawn#1036]
Hi!

I'm trying to add a background color to some text(user input of arbitrary length) to make it look something like a text area on pdf.

Here is an example:

```
class HighlightCallback
    def initialize(options)
      @color = options[:color]
      @document = options[:document]
    end

    def render_behind(fragment)
      original_color = @document.fill_color
      @document.fill_color = @color
      @document.fill_rectangle([@document.bounds.left, fragment.top],
                               @document.bounds.width,
                               fragment.height)
      @document.fill_color = original_color
    end
  end

 Prawn::Document.generate("example.pdf") do |pdf|
   highlight = HighlightCallback.new(color: 'cfeaf8', document: pdf)
   text = "I have a new \n\n lines \n\n inside!"
   pdf.formatted_text([{text: text, size: 9, callback: [highlight]}])
 end
```

Unfortunatelly blank lines have no background in this case (apparently they are not 'fragments')

![example](https://user-images.githubusercontent.com/16029673/28366770-d2e68b24-6c96-11e7-918a-26ef58733e84.png)

Can it be avoided?

**Comment by Kulgar** [comment]
@ViktorKopychko : I managed to do this by adding the "indent_paragraphs" option, like this: 

```ruby
    def add_text(text, highlight, pdf, indent=0, color="000000")
      pdf.formatted_text [{
        :text => (Prawn::Text::NBSP * indent) + text.gsub("\r\n", "\r\n#{Prawn::Text::NBSP * indent}"),
        :color => color,
        :callback => highlight
      }], :indent_paragraphs => 0
    end
```

Thanks to that, the blank lines are taken into account as fragments (don't know why though).

You can then use NBSP to indent your paragraphs. I don't know if there is a better solution, but this works. 

Nevertheless, the use of NBSP is already required to indent your text, as if you only use the "indent_paragraphs" option you will see that the background color only begins at the first letter, leaving a blank space where text is indented.

**Comment by ViktorKopychko** [comment]
@Kulgar
Thanks a lot for the reply, I've managed to do this featre using fill_rectagle, but still good to know
