### ISSUE TITLE
prawnpdf iframe

### ISSUE THREAD

**Issue by Frank004** [prawnpdf/prawn#1037]
Hi, I'm looking for a way to render the pdf generate in an iframe.

My problem is I'm using the inline display and it renders the mysite.com/stuff.pdf and on mobile, the user gets stuck on the pdf because it doesn't have the navigación bar from the browser or the navigation from my app.

![screen shot 2017-07-26 at 11 21 08 am](https://user-images.githubusercontent.com/7242689/28629138-90e72ee6-71f4-11e7-9d2d-e415f3a58863.jpg)

**Comment by pointlessone** [comment]
Hello Francisco,

Make your View PDF button open an iframe with a PDF in it.

---

I would like to pint out that this is not related to Prawn in any way. This is not a Prawn bug, nor it is a feature request. We have a mailing list for community discussions with a little less strict topic requirement. Fell free to use it the next time.

**Comment by Frank004** [comment]
Thank you I will
