### ISSUE TITLE
collision

### ISSUE THREAD

**Issue by xor256** [prawnpdf/prawn#1039]
Is possible to check intersections 2 glyphs from font?
for example i get font and 2 glyphs
'P' and 'i' 
how minimal distance is between 'Pi' or how put i distance X pt betwen P.
(distance = minimal distance is X pt)

**Comment by gettalong** [comment]
What you can do is try to use ttfunk to get the metrics of the glyphs. Each glyph has a horizontal advancement, i.e. the x-distance from the current origin to the the point of the next placement of the glyph origin.

However, there are additional measurements (also see http://chanae.walon.org/pub/ttf/ttf_glyphs.htm, in roughly the middle of the page), namely xMin and xMax which are, respectively, the left and right side of the bouding of the glyph.

Those two could be used to do what you want:

* Paint the 'P' glyph on the canvas
* Move the point of origin `P_horizontal_advancement - P_x_max - i_x_min` to the left
* Paint the 'i' glyph on the canvas

**Comment by gettalong** [comment]
@xor256 Did my comment help and can we close this issue? Or is this still a problem and you need further information?

**Comment by pointlessone** [comment]
TTFunk partially supports glyph outlines. It still would require a lot of work to interpret those outlines and find distances. I'd say, this kind of usage is out of scope for both Prawn and TTFunk.
