### ISSUE TITLE
to markdown conversion possible?

### ISSUE THREAD

**Issue by ghost** [prawnpdf/prawn#1040]
I just noticed: https://github.com/johnlinp/pdf-to-markdown

And I wondered whether we have this available in prawn?

I am not sure if it would be a good fit anyway but I just thought that to-and-from conversions may be useful; and .md should be very trivial compared to e. g. parsing HTML/XML.

Anyway, please do feel free to close this issue request here at any moment in time.

**Comment by gettalong** [comment]
@pointlessone FYI: The user requesting this has been deleted and since Prawn is a PDF generation library, a conversion *from* PDF to another format is not a good fit. Therefore I close this issue.
