### ISSUE TITLE
Prawn data folder not present in the gem

### ISSUE THREAD

**Issue by fidalgo** [prawnpdf/prawn#1041]
Since I've found if it's  deliberate or not to not have included the `images` and `fonts` directories of the `data` folder, in the gem, I'm opening this issue for clarification.

Currently the [prawn-table](https://github.com/prawnpdf/prawn-table) needs the `prawn.png` image to be present in the gem, in order to run the tests.

Also if you run `rake spec` inside the prawn installation directory you'll have a lot of tests failing because the missing images and fonts.

If someone can provide some clarification on this, I can open a Pull Request to add the data, if this is the way to go.

**Comment by pointlessone** [comment]
Rubygems have long ago abandoned idea of complete distribution. It has removed automatic test running upon gem installation. And it's not recommended to package tests any more. So you should not expect `rake test` to work in the installed gem directory. You need the repo for that. That said, we should package files required at runtime. We should package `.afm` files.

**Comment by petergoldstein** [comment]
@pointlessone This can probably be closed.  The `afm` files are included in the distribution, and the `prawn-table` image issue is now resolved.
