### ISSUE TITLE
Is it possible to have a transparent page background?

### ISSUE THREAD

**Issue by caseyohara** [prawnpdf/prawn#1046]
By default, every page has a white background. Is it possible to have a transparent background/no page background?

**Comment by gettalong** [comment]
PDF is, more or less, designed to be printed. It didn't have transparency at all until version 1.4. You will find that the background is something the viewer displays, and not something the PDF file itself defines (normally). Therefore no, not possible because it depends on the viewer.

**Comment by pointlessone** [comment]
Just in case, unless you explicitly put anything on a particular part of the page it won't be printed white. For example, if you put a black squire in the middle of a page you'll see it on white background on your screen, but if you print it on a red sheet of paper you'll get a black square on red background. In that sense all PDFs are transparent.

As Thomas said, background color is not defined in the PDF. Most renderers that output to screen assume white as it's the most common color of paper. If you want to use your document as vector graphics, most image editors (that I used) that understand PDF allow import with transparent background.

**Comment by caseyohara** [comment]
Great explanations @gettalong and @pointlessone, thanks!

Yes, I was experimenting with using a single-page document for vector graphics. Chrome and Preview were both displaying it with a white background. Makes sense that those renderers assume a white background but image editors would assume a transparent background. Thanks for your help.
