### ISSUE TITLE
Calling inspect on Prawn::Document is very slow

### ISSUE THREAD

**Issue by thedjinn** [prawnpdf/prawn#1062]
Hi! I encountered a strange bug. When I call `inspect` on a `Prawn::Document` instance the result takes a few minutes to generate while eating lots of memory and CPU. This can be annoying when e.g. a `NoMethodError` is raised, which inspects the document object in its exception message.

A quick google found some similar issues in other projects:

https://github.com/rails/rails/issues/1525#issuecomment-4075591
https://github.com/rom-rb/rom-repository/pull/65

I'm using Ruby 2.5.0p0.

**Comment by pointlessone** [comment]
In general case you shouldn't do that. Document contains a tonne of state but presentation doesn't provide much useful information since most of it is internal stuff. We left default Ruby implementation because we don't have a useful replacement.

**Comment by thedjinn** [comment]
Absolutely and that makes perfect sense. The problem however is that (in my case) a `NoMethodError` raised when developing with Prawn hangs because Ruby tries to print the exception message, and `NameError` and its subclasses call inspect internally when generating that message.

**Comment by pointlessone** [comment]
Yes, I see the problem. You're welcome to suggest a solution.

**Comment by thedjinn** [comment]
Well, the quickest fix that works for me is a simple patch that lets `inspect` call `to_s`. Looking at the Ruby source code, `inspect` calls `to_s` when there are no instance variables on itself so it prints something like `#<Prawn::Document:0x00007fa9c0e884d0>` and thus omits the instance variables that cause the endless recursion (because `inspect` calls `inspect` on its ivars if they have ivars themselves).

```ruby
class Prawn::Document
  def inspect
    to_s
  end
end
```

This patch prevents symptoms while still providing decent behaviour, but an even better approach might be to determine which specific ivar (or actually its class) causes the problem and patch that class instead.

**Comment by swistak** [comment]
Also encountered this, also by Ruby hanging completely while trying to report `NoMethodError` on a instance of Prawn::Document

Took me hours to figure out and what's causing it, then with that knowledge I googled and stumbled upon this.

I second the suggestion to just provide either simplest `inspect` output based on `to_s` or alternatively provide minimal amount of state.

**Comment by petergoldstein** [comment]
@pointlessone What are your feelings on the proposed solution?

**Comment by pointlessone** [comment]
@petergoldstein Alias will do.

**Comment by petergoldstein** [comment]
@pointlessone  This is addressed by #1254 and should be closed.
