### ISSUE TITLE
PDF/A integration of embedded xml

### ISSUE THREAD

**Issue by ck2000** [prawnpdf/prawn#1063]
Is is possible to create PDF/A-3 files using prawn (embedded xml)? 

PDF/A is an ISO-standardized version of the Portable Document Format (PDF) specialized for use in the archiving and long-term preservation of electronic documents.

Futher information can be found here:
https://en.wikipedia.org/wiki/PDF/A

**Comment by pointlessone** [comment]
There's no built-in support but you can create PDF object directly and thus embed the metadata. I believe there were examples somewhere: either here in issues, or on the mailing list.

---

I will close this issue now. Feel free to reopen if you have anything to add to the discussion.

**Comment by Sylvain** [comment]
Hi @ck2000 did you find some resources to create PDF/A with prawn ?

**Comment by ck2000** [comment]
No, I did not find a solution.

**Comment by Sylvain** [comment]
Thank you for your quick answer!
