### ISSUE TITLE
accessibility: set Advanced/ReadingOption -> Language

### ISSUE THREAD

**Issue by davideghz** [prawnpdf/prawn#1077]
Hi

I'm able to add info attributes to a newly generated PDF using something like:

```
info = { :Title => "Sample METADATA",
             :Author => "Me",
             :Subject => "My Subject",
             :CreationDate => Time.now }

@pdf = Prawn::Document.new(:template => filename, :info => info)
```

To make the PDF accessible by text reader I need to set the  Language ReadingOption. How can I achieve that using prawn? I didn't find any reference in the codebase and in the docs

**Comment by gettalong** [comment]
@davideghz Could you point to the section in the PDF 1.7 specification (https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf) where it talks about this Language ReadingOption? I didn't find anything about it.

**Comment by davideghz** [comment]
Hi @gettalong check section **9.8: Natural Language Specification**

https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/pdf_reference_archives/PDFReference.pdf

**Comment by gettalong** [comment]
Thanks for the pointer to the natural language specification (section 14.9.2 in the official ISO PDF 1.7 spec).

So you want to set the language that is used by the document or a part of it. As described in the mentioned section there are potentially several ways to do that but only the first, setting it on the whole document, is easy to do with Prawn (I don't know if the other options would work at all...).

Section 7.7.2 "Document Catalog" describes the main dictionary of a PDF file, and this catalog dictionary has a key named `Lang` that needs to be set to a text string specifying a language in the [RFC 3066 form](https://www.ietf.org/rfc/rfc3066.txt), e.g. `en-US`.

The document catalog can be accessed in Prawn through `state.store.root`. To set the necessary `Lang` key, you need to do something like `state.store.root.data[:Lang] = LANG`.

Here is a full example:

~~~ ruby
require 'prawn'
Prawn::Document.generate('out.pdf') do |pdf|
  pdf.text "test"
  pdf.state.store.root.data[:Lang] = 'en-US'
end
~~~

**Comment by gettalong** [comment]
@davideghz I think this issue can be closed. If I mistaken, please comment!

**Comment by JoeOsterfeld** [comment]
Can we reopen this issue? I've attempted the strategy described above, and it's not changing the language property read by Adobe Acrobat. 
![Screen Shot 2020-09-02 at 10 54 09 AM](https://user-images.githubusercontent.com/25331597/91999660-a2806200-ed0a-11ea-8395-126f471872b9.png)

Code: 
```
  def pdf
    @pdf ||= Prawn::Document.new({ :info => metadata})
  end

  def build_pdf
    pdf.state.store.root.data[:Lang] = 'en-US'
    title
    header_images
    agent_contact_section
    coverage_type_section
    business_type_section
    insured_contact_section
    question_answer_section
    disclaimers_section if disclaimers.any?
    signature_section if has_signature_section
    footers
    pdf.render
  end
```

**Comment by gettalong** [comment]
@JoeOsterfeld Can you provide the generated PDF for inspection? If not, can you run `hexapdf inspect FILE.PDF c` (installable via `gem install hexapdf`) and provide that output?

**Comment by reiz** [comment]
I just tested it with this code: 

```
Prawn::Document.generate("/Users/u2/prawn.pdf") do |pdf|
   pdf.state.store.root.data[:Lang] = 'de-DE'
   pdf.text "test doc"
end
```

And it worked for me. Adobe Acrobat shows the correct language. 

<img width="618" alt="Screenshot 2024-02-18 at 18 27 40" src="https://github.com/prawnpdf/prawn/assets/652130/7358511d-72f0-48f5-8eb0-edda5638402c">
