### ISSUE TITLE
Expose invalid windows 1252 replacement as option

### ISSUE THREAD

**Issue by toxaq** [prawnpdf/prawn#1078]
Currently due to the font restriction in the PDF generation, we're limited to windows-1252 without using font substitution. In my instance, I don't currently require any characters outside this restricted range. However, in the encoding conversion, the most basic conversion is used.

    def normalize_encoding(text)
        text.encode('windows-1252')
    end

This throws an error if the char is not convertible (eg U+2028) which is decorated as: 
 
    Prawn::Errors::IncompatibleStringEncoding occurred 
    Your document includes text that's not compatible with the Windows-1252 character set.
    If you need full UTF-8 support, use TTF fonts instead of PDF's built-in fonts.

Rather than allocate a font, I'd just like to ignore all of the invalid characters and use someone thing like:

    def normalize_encoding(text)
        text.encode('windows-1252', invalid: :replace, undef: :replace, replace: '?')
    end

I've done this as monkey patch in my code but was wondering if this would be worth a pull-request as a configuration option?

**Comment by pointlessone** [comment]
You're absolutely free to normalize or filter text before you're giving it to Prawn if you want to only use Windoes-1252 encoding. Monkey patching is an option as well but it is not supported and in no way encouraged.

We have no intention of implementing proposed feature. It'll raise more issues than solve.

---

I'm closing this issue for the aforementioned reason. Feel free to reopen if you feel a broader discussion needs to take place.

**Comment by toxaq** [comment]
Glad I asked. Yes, I appreciate that I can filter text before provided to a library however the library gave the illusion that it could handle the UTF-8 I gave it. Is there a way to filter all text passed to prawn or would I need to do for each single piece of text I pass it? 

I'd be interested to understand why you think throwing an exception raises less issues than a configuration option to change behaviour from an exception throwing default. I don't want to only use windows-1252 encoding but it's all that this library supports without additional configuration. Getting exceptions thrown because someone copied invisible UTF whitespace is a fun way to learn about the limitations of the library that aren't immediately obvious. The documentation states:

> Comprehensive internationalization features, including full support for UTF-8 based fonts, right-to-left text rendering, fallback font support, and extension points for customizable text wrapping.

Perhaps a pull request for the documentation would suffice to state that it supports externally supplied UTF-8 fonts but only supports UTF-8 that's easily convertible to windows-1252 out of the box (unless I'm missing something around the exception I'm seeing here).
