### ISSUE TITLE
No support for TTF files with CBDT Tables like NotoColorEmoji.ttf

### ISSUE THREAD

**Issue by plntyk** [prawnpdf/prawn#1081]
Not all ttf fonts are usable in prawnpdf.

file NotoColorEmoji.ttf
````
NotoColorEmoji.ttf:
TrueType Font data, 13 tables, 1st "CBDT", 15 names, 
Microsoft, language 0x409, Copyright 2013 Google Inc.Noto Color EmojiRegularVersion 2.017;
GOOG;noto-emoji:20180810:f1da3bc
````
Using Symbola.ttf with: TrueType Font data, 13 tables, 1st "GDEF"

is Successful in examplefile:
````
require "prawn"

Prawn::Document.generate("test.pdf") do 
 text " HELLO "

font "#{Prawn::DATADIR}/fonts/Symbola.ttf"
 text "♉♊♋"
end
````

**Comment by gettalong** [comment]
`ttfunk` only supports TrueType font outlines and not bitmap data. It will support OTF fonts with CFF tables in a near-future version but there is currently no one working on bitmap data support.

Please open a feature request at the https://github.com/prawnpdf/ttfunk repository if you need bitmap data support.
