### ISSUE TITLE
Page numbers are overlapped by repeated rectangle

### ISSUE THREAD

**Issue by Sholac** [prawnpdf/prawn#1086]
I have some kind of footer which will show only if multiple pages and not last:
```
if (num_pages = page_count) > 1
      repeat(lambda {|pg| pg < num_pages}) do
        fill_rectangle [0, 40], 540, 40
        text_box "Bestellt durch", :size => 8, :width => 60, :at => [15, 20]
      end
    end
```
And than at the end of file, i have page numbers like this
```
options = { :at => [bounds.right - 110, 5],
                :width => 100,
                :align => :right,
                :start_count_at => 1,
                :color => font_color,
                :size => 8}
    number_pages "Seite <page> von <total>", options
```
If PDF have more pages than that footer will overlap page numbers, not sure why.
In provided PDF I moved page numbers a bit below so you can see it. By design, numbers should be in gray box, few px up.

[LieferscheinPageNumbers.pdf](https://github.com/prawnpdf/prawn/files/2533767/LieferscheinPageNumbers.pdf)

**Comment by pointlessone** [comment]
Page numbering and repeaters use different mechanisms.

Page numbering takes place at the call, while repeaters after everything. So in your case, repeaters are getting called after page numbering. You may need to implement page numbering yourself if you want a different draw order.

---

I will close the issue now. Feel free to reopen if you feel like your issue have not been resolved.
