### ISSUE TITLE
I am not able to add hyperlinks in pdf report index page 

### ISSUE THREAD

**Issue by shagun-gupta** [prawnpdf/prawn#1094]
I am using this code to generate hyperlinks

                    text '<link anchor="hello">Click me</link>', inline_format: true
                    add_dest "hello", dest_xyz(bounds.absolute_left, y)

**Comment by gettalong** [comment]
Please provide a simple Ruby script to reproduce the problem - thank you!

**Comment by pointlessone** [comment]
I tried these two lines of code and it seem to work OK. The text is clickable. The page jumps to the specified position.

I'm closing this issue as everything seem in order. Feel free to reopen with more details if something doesn't work for you.
