### ISSUE TITLE
Invalid breaks in words with accents

### ISSUE THREAD

**Issue by ogmios-voice** [prawnpdf/prawn#1098]
Converting the following asciidoc document to pdf (using asciidoctor-pdf-1.5.0.alpha.17.dev w/ prawn-2.2.2)

```
:pdf-page-size: a5

= test

aàbècìdòeùf gáhéiíjókúlým nâoêpîqôrûs tñuõvãw xäyëzïaöbücÿd
aabbccddeef gghhiijjkkllm nnooppqqrrs ttuuvvw xxyyzzaabbccd
```

results in an invalid break in the first row. The resulting block of the pdf looks like this (for me):

```
aàbècìdòeùf gáhéiíjókúlým nâoêpîqôrûs tñuõvãw xäyëzïa
öbüc d
aabbccddeef gghhiijjkkllm nnooppqqrrs ttuuvvw
xxyyzzaabbccd
```
(Note: the ÿ character is invisible in the result, but that is a font issue.)

But the breaks should be consistent, while the current position of the break depends on whether a given letter is accented or not. The correct output should be:

```
aàbècìdòeùf gáhéiíjókúlým nâoêpîqôrûs tñuõvãw
xäyëzïaöbücÿd
aabbccddeef gghhiijjkkllm nnooppqqrrs ttuuvvw
xxyyzzaabbccd
```

See also: https://github.com/asciidoctor/asciidoctor-pdf/issues/979#issuecomment-450698668

**Comment by gettalong** [comment]
Can you provide a simple Ruby script (no dependencies except Prawn) to reproduce the problem?

**Comment by ogmios-voice** [comment]
Unfortunately I can't. I don't have too much ruby experience, no experience at all with Prawn, and I will lack any free time in the following period.

**Comment by gettalong** [comment]
No problem! Just note that the issue resolution may take longer without such a script.

**Comment by pointlessone** [comment]
I'm closing it in favour of #1295. I don't think fixing just accented characters would be useful or even possible without addressing the bigger issue.
