### ISSUE TITLE
TTF files not installed

### ISSUE THREAD

**Issue by waghanza** [prawnpdf/prawn#1099]
Hi @pointlessone,

I can see that some **ttf** fonts are present in https://github.com/prawnpdf/prawn/tree/master/data/fonts

However, I can in https://github.com/prawnpdf/prawn/blob/2.2.0/prawn.gemspec#L17  that `.ttf` files are not provided / installed on `gem install prawn`.

Why is that ?

Regards,

**Comment by pointlessone** [comment]
The fonts are used in tests. Since tests are not packaged there's no point in packaging the fonts.

**Comment by waghanza** [comment]
OK. I understood

However,  `ttf` fonts could be useful for **utf-8** support

**Comment by pointlessone** [comment]
While true, the fonts in the repo don't have good coverage. And any font with near to full coverage would make the gem weight tens of MB. A free font with a decent coverage (and good looking on top of that) is very hard to find, too.

I consider it to be out of scope of this gem to provide fonts. Users are expected to find fonts that suit their design and cover intended text themselves. It's also up for users to decide if they want to provide full Unicode coverage with a fallback font.

**Comment by waghanza** [comment]
I agree :tada: with this

I have to find a way to fix my `rails` issue

Thx

**Comment by waghanza** [comment]
@
