### ISSUE TITLE
how-to-modify-variable-data

### ISSUE THREAD

**Issue by mtkNamwhan** [prawnpdf/prawn#1106]
https://stackoverflow.com/questions/21690130/how-to-modify-variable-data-in-pdf-templates-with-prawn-if-possible

**Comment by pointlessone** [comment]
Short answer: no.

Longer: Prawn doesn't support template. It used to but the gem (`prawn-templates`) is retired now. Your best shot with Prawn is to recreate the template in code.

---
I'm closing this issue now. Feel free to reopen if you have any additional information or feel like your question wasn't answered.
