### ISSUE TITLE
Multiple copies

### ISSUE THREAD

**Issue by BernardoMG** [prawnpdf/prawn#1109]
Hi, 

I'm generating multiple copies of the same document and save it on the same PDF file, e.g.:

```ruby
document = Prawn::Document.new

number_of_copies.times do 
  (1..number_of_copies).each { |index| generate_content(document, index) }
end
```

`generate_content` method basically adds the same pages to the document and resets the page number
 
It's possible to optimize this with Prawn? I'm trying to avoid multiple generations of the same content...

[Related closed issue](https://github.com/prawnpdf/prawn/issues/506)

Thanks a lot!

**Comment by pointlessone** [comment]
There's no way you can optimize it. This is your best option.

---

I'll close this issue now. Feel free to reopen if you have anything to further discussion.
