### ISSUE TITLE
Streching fonts in yAxis

### ISSUE THREAD

**Issue by douglasep** [prawnpdf/prawn#1116]
I use <b>PrawnPDF</b> to render Poster's PDF. These posters are used to show product prices, so they big size is really important to us.

So I need to strech the <b>yAxis</b> of the price's <b>font</b> as we do in <em>CSS3</em> by using:

`transform: scale(1,1.25);`

Has anyone faced this problem before? Many Thanks.

**Comment by pointlessone** [comment]
It's not documented well and not very ergonomic but you can try using [`transformation_matrix`](http://prawnpdf.org/api-docs/2.0/Prawn/Graphics/Transformation.html#transformation_matrix-instance_method).

---

I'll close this issue now. Feel free to reopen if you have any additional information or feel like your issue hasn't been resolved.
