### ISSUE TITLE
Published 2.2.2 gem requires pdf-core 0.7.0

### ISSUE THREAD

**Issue by mgmodell** [prawnpdf/prawn#1120]
I'm trying to update my gems and it seems the published version of prawn requires pdf-core 0.7.0 rather than the latest (0.8.1). I'm looking at the latest source from GitHub and it requires 0.8.1 and the tests seem to run properly, but the gem bundler is pulling is incorrect. Is there a reason for this? Am I just being dense?

Gemfile including:

    gem 'prawn', '2.2.2'
    gem 'prawn-table', '0.2.2'
    gem 'pdf-core', '0.8.1'

`bundle update` yields:
Bundler could not find compatible versions for gem "pdf-core":

    In Gemfile:
      pdf-core (= 0.8.1)

      prawn (= 2.2.2) was resolved to 2.2.2, which depends on
        pdf-core (~> 0.7.0)

**Comment by pointlessone** [comment]
pdf-core had an extra release after prwn 2.2.2. The dependency was updated in the prawn repo but it has not been released yet.

**Comment by mgmodell** [comment]
OK. Thanks!
