### ISSUE TITLE
Can't render image and font 

### ISSUE THREAD

**Issue by anoopkvenu** [prawnpdf/prawn#1129]
I am using the following code to render image and PDF
```
font_families.update("new_font" => {
          :normal => Rails.root.join("app/assets/fonts/new_font.ttf").to_s,
          :bold => Rails.root.join("app/assets/fonts/new_font.ttf").to_s
      })
      font "new_font"
image Rails.root.join("app/assets/images/test.png").to_s, :position => :right, :width => 150, :vposition => -10
```
I am having strange error. The following work perfectly in my local system. But when I run this code in server image will be blank and font is not changing.

**Comment by pointlessone** [comment]
It looks like it's an environment issue and not Prawn.

I'd check if your deployed application has access to the files. I.e. check file/directory permissions.

---

I'll close this issue now since it doesn't look like a Prawn bug. Feel free to reopen if you find it actually is.

**Comment by anoopkvenu** [comment]
@pointlessone I tried it by giving an image URL from public sources. Still, get the same issue,
