### ISSUE TITLE
Font metric cache doesn't work properly in Ruby 2.7

### ISSUE THREAD

**Issue by mojavelinux** [prawnpdf/prawn#1140]
The font metric cache doesn't work properly in Ruby 2.7. It's not properly considering the font size when resolving the string width, which can lead to incorrect results if the same string with a different size had previously been cached.

This seems to be due to a change in how Ruby uses a Struct for a hash key. It's not calling `#hash` on each property. And since the Font object is mutable, two different font sizes can end up resolving to the same key.

A quick fix is to invoke `#hash` on the font when initializing the CacheEntry:

```rb
CacheEntry.new f.hash, options, encoded_string
```

I'm having a hard time reproducing outside of the application because it highly depends on the call order. But the main issue is that the font size of a font can change, which in turn changes the key in the hash. There's a note in the code that defining a hash method on Font fixes the issue, but that assumption doesn't seem to hold true anymore.

**Comment by joeyschoblaska** [comment]
Thank you! I ran into this bug and was going crazy trying to figure out what was wrong. Here's a minimal reproduction:

```ruby
# $ ruby -v
# ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
# $ gem info prawn
# prawn (2.2.2)

require "prawn"

Prawn::Document.generate("output.pdf") do
  font("Helvetica", size: 42, style: :bold) do
    text "A big header"
  end

  font("Helvetica") do
    text "A big header foo."
    text "<strong>A big header</strong> foo.", inline_format: true
    text "Something else."
    text "<strong>Something else</strong> foo.", inline_format: true
  end
end
```

![Screen Shot 2020-06-14 at 6 21 44 PM](https://user-images.githubusercontent.com/29129/84606453-f72ee200-ae6b-11ea-8f5f-4ed863571776.png)

[output.pdf](https://github.com/prawnpdf/prawn/files/4777384/output.pdf)

**Comment by mojavelinux** [comment]
@pointlessone Can you confirm 73be039575a6e793235d03c4640da309e57b9ebf fixes this issue? I want to make sure people following the issue are aware that it may now be fixed.

**Comment by pointlessone** [comment]
@mogest Confirm.

**Comment by bhb** [comment]
@mojavelinux Confirm from me as well.

**Comment by brandoncc** [comment]
First, thank you all for finding and fixing this bug.

Unfortunately, I just spent an entire day chasing down this bug. Is there any chance a new version could be cut so that nobody else has to do the same since it has been fixed in master for almost two years?
