### ISSUE TITLE
Embedded TTF font will not open in Adobe Reader: "Cannot extract the embedded font"

### ISSUE THREAD

**Issue by jeffblake** [prawnpdf/prawn#1142]
Starting a new issue for visibility, but this 10 year old issue is also relevant: https://github.com/prawnpdf/prawn/issues/94

I'm using Open Sans from the google font website.

Attached sample PDF. It opens fine in Chrome, Mac Preview, but will not open in Adobe Acrobat (latest mac version)

When opening, the error is: "Cannot extract the embedded font '9ab1c0+OpenSans-Bold'. Some characters may not display or print correctly."

Relevant code from installing custom TTF font:

```
    font_families.update('Open Sans' => {
      normal: Rails.root.join('app', 'fonts', 'OpenSans-Regular.ttf').to_s,
      bold: Rails.root.join('app', 'fonts', 'OpenSans-Bold.ttf').to_s,
      italic: Rails.root.join('app', 'fonts', 'OpenSans-Italic.ttf').to_s,
      bold_italic: Rails.root.join('app', 'fonts', 'OpenSans-BoldItalic.ttf').to_s
    })
    font 'Open Sans', style: :normal
```

Honestly I would be fine using the default system font and not bothering with embedded TTF fonts, but then I lose portability and UTF-8 support. Any ideas?

Environment
Ruby 2.6.5
[Christy Sheppard (1).pdf](https://github.com/prawnpdf/prawn/files/4055647/Christy.Sheppard.1.pdf)

**Comment by hjansen** [comment]
Same problem here, just appeared over night with no changes to our sources

**Comment by hjansen** [comment]
I seems to be related with the update of ttfunk. Rollback to ttfunk version 1.5.1 seems to be a workarround for now:
https://github.com/prawnpdf/ttfunk/issues/72

**Comment by excid3** [comment]
Just got notified by a user that the same thing is happening for our PDFs. Thanks for the tip about ttfunk @hjansen 👍

**Comment by pointlessone** [comment]
This issue should be fixed in TTFunk 1.6.2. Please upgrade and report any issues you have. Thank you for patience.

**Comment by kevinchugh** [comment]
This "unable to extract" issue is happening for me with ttfunk 1.7 was the fix reverted?

**Comment by giuseb** [comment]
I am experiencing the same problem with TTFunk 1.8
