### ISSUE TITLE
Text printing wrong gliphs

### ISSUE THREAD

**Issue by NicosKaralis** [prawnpdf/prawn#1144]
I've generated a PDF with prawn, as I did several times in different projects. On the computer, it appears fine. But when  I print it, I get illegible text, like in the picture bellow

![IMG_3881](https://user-images.githubusercontent.com/627404/73744543-48f28d80-4751-11ea-8492-c157ac140226.jpg)

As you can see, the image is readable, but every text is broken

Every computer opens it fine. Other projects were built using the same font (and same base code) and they print it fine.

What could possible be the issue here?

**Comment by pointlessone** [comment]
Any chance you use ttfunk 1.6.*?

**Comment by NicosKaralis** [comment]
Yes, ttfunk (1.6.1)

**Comment by pointlessone** [comment]
Please try downgrading to 1.5.* and let me know if you see the issue on printer.

**Comment by NicosKaralis** [comment]
Solved, downgrading ttfunk worked fine

**Comment by pointlessone** [comment]
Thank you for your feedback.
Sorry for the inconvenience.

**Comment by arnaudlevy** [comment]
Hi, fixes indeed when printed with Acrobat, but Aperçu on a Mac is still messed up. Any clue?
