### ISSUE TITLE
Create fillable forms

### ISSUE THREAD

**Issue by simmerz** [prawnpdf/prawn#1149]
Is is possible to create fillable forms (not to fill them) - I'd love to create a form PDF which could be uploaded to an esign provider or be signed in Acrobat for instance.

**Comment by gettalong** [comment]
You can try [prawn-blank](https://github.com/hannesg/prawn-blank/).

**Comment by carloferrer** [comment]
+1 to @simmerz's ask, and also surprised this isn't a thing native to `prawn`. I looked at @gettalong's suggestion of `prawn-blank` but I have reservations on account of the last commit being 7 years ago and zero documentation.

**Comment by gettalong** [comment]
@carloferrer @simmerz That's fair with regards to the *original* prawn-blank. I searched a bit and found https://github.com/DocSpring/prawn-blank which has been updated more recently.

**Comment by gettalong** [comment]
@simmerz @carloferrer I will close this issue now since this feature will most probably not appear in prawn itself. The DocSpring fork of prawn-blank can be used for forms.
