### ISSUE TITLE
can't modify frozen String (FrozenError) with external fonts

### ISSUE THREAD

**Issue by tdegrunt** [prawnpdf/prawn#1150]
The error I'm getting: 
prawn-2.2.2/lib/prawn/font/ttf.rb:319:in `block in embed': can't modify frozen String (FrozenError)

When I try this against the master branch, it's working fine. Could you perhaps release a new version?

*ttc.rb:*
```ruby
# frozen_string_literal: false
require 'prawn'

document = Prawn::Document.new do |pdf|
  pdf.font 'DejaVuSans.ttc'
  pdf.text 'Gołąbki'
end

document.render_file 'font.pdf'
```

DejaVuSans.ttc is from prawn's own repo, I can't attach it to this ticket.

I'm running this with:
```RUBYOPT=--disable=frozen-string-literal ruby ttc.rb```

**Comment by klyonrad** [comment]
@tdegrunt why do have the `frozen_string_literal: false` in the test file and why do you run it with `--disable=frozen-string-literal`? Does this have to do with the issue?

is this still happening for you with prawn 2.4.0?

(never observed this issue with TTF fonts)

**Comment by tdegrunt** [comment]
Good points, I had `frozen_literal: true` initially, but then commented it out to see it working, that god pasted in this ticket sadly. I'm using 2.4 these days, that doesn't have the issue. Thanks for coming back on this, this issue can be closed though.

**Comment by petergoldstein** [comment]
@pointlessone Per @tdegrunt 's last comment, this issue can be closed.
