### ISSUE TITLE
is it possible to add google maps

### ISSUE THREAD

**Issue by andybuki** [prawnpdf/prawn#1151]
Is it possible to add google maps to pdf

**Comment by gettalong** [comment]
You need to use another tool to convert the map to an image (PNG or JPEG) and then you can include it in the PDF.

**Comment by pointlessone** [comment]
You can use [Google Maps Static API](https://developers.google.com/maps/documentation/maps-static/intro) to embed an image of a map. You can't use interactive maps.

---

I'll close this issue. Feel free to reopen if you feel it was not resolved.
