### ISSUE TITLE
Documentation detail of link_annotation with :Desc option

### ISSUE THREAD

**Issue by aamir-nazir** [prawnpdf/prawn#1155]
I have been struggling to link a text heading with a specific page in the Pdf, similar to the linking of `Table of Contents` in the Pdf file. I have found `link_annotation` method to achieve this however there isn't suffice documentation/examples available to use `link_annotation` method with `:Desc` option.

**Any ideas how to use `link_annotation` with `:Desc` option?**

Link Annotation Documentation: https://www.rubydoc.info/gems/prawn-core/Prawn%2FDocument%2FAnnotations:link_annotation

**Comment by gettalong** [comment]
See https://www.rubydoc.info/gems/pdf-core/PDF/Core/Destinations for how to create suitable `Dest` objects. You will probably want something like `#dest_fit`, together with `prawn_document.state.pages[i]` for getting the ith page.

Please close the issue if this solves your problem.

**Comment by aamir-nazir** [comment]
@gettalong thanks for your response.

I have already reviewed `Destinations` but unsure what keys and structure should be provided to the `link_annotation` to make it work as there isn't any example available.

I found one example on StackOverflow: https://stackoverflow.com/questions/20855498/prawn-pdf-generator-make-image-with-link, it clearly delineated usage of `link_annotation` with `:A`.

I am looking similar example for `:Desc`.

**Comment by gettalong** [comment]
You don't need to construct the needed `Dest` object yourself, that's what the helpers I pointed you to are for. They create the needed array structure for `:Dest`.

So something like `link_annotation([left, top, bottom, right], Dest: dest_fit(state.pages[0]))` should link to the first page of the document.

**Comment by aamir-nazir** [comment]
This has resolved the issue.  Much appreciated, Thanks

**Comment by aamir-nazir** [comment]
Before finally closing this issue, I would like to clarify one more thing.

In order to align page's top at specific offset I tried to use method `#dest_fit_horizontally` but it always align page's top in the viewport instead of offset passed in the parameter. i.e
`dest_fit_horizontally(200.0, state.pages[2])`

**Comment by gettalong** [comment]
Hmm... according to the spec: *"Display the page designated by page, with the vertical coordinate top positioned at the top edge of the window and the contents of the page magnified just enough to fit the entire width of the page within the window. A null value for top specifies that the current value of that parameter shall be retained unchanged."*

So this should do what you want. If it is possible, could you attach a sample PDF that shows that issue? And have you tried different PDF viewer applications?

You could also try using [`#dest_xyz`](https://www.rubydoc.info/gems/pdf-core/PDF/Core/Destinations#dest_xyz-instance_method) instead and see if that works for you.

**Comment by aamir-nazir** [comment]
Here is the link to Pdf and its code sample: https://drive.google.com/open?id=1BmR1BL-F4GX6ueKxUmMnKCtlpMQApTgi

I haven't tried any other PDF viewer application and using Preview application of OS X to view the pdf file. I have another PDF file generated manually is working fine in Preview.

Regarding `#dest_xyz`, I have already tried this method. When PDF is generated using this method, PDF viewer says it's broken or corrupt. In fact I have tried all of the destination methods. It seems like offset parameter is not working at all. May be I am doing something wrong. To sort this out I have added both code and its output PDF.

**Comment by gettalong** [comment]
@aamir-nazir Thank you for the sample PDF. I tried it with two different PDF viewers, evince and okular, and it works correctly in both.

Here is a screenshot from okular showing the result of clicking:

![screenshot-prawn](https://user-images.githubusercontent.com/4104/79024167-6d6c4b00-7b82-11ea-88ac-31d189855f88.png)

Do you see the gray rectangular area in the thumbnail preview? That represents the current part of the PDF that is shown in the main window. As you can see it correctly moved to the 200 point horizontal line (remember that the origin is in the lower left!). The sample code looks fine.

You wrote you have a PDF that works fine with Preview? Could you provide that for inspection to see what may be the difference?

**Comment by aamir-nazir** [comment]
Please check this PDF: https://courses.edx.org/c4x/DelftX/ET.3034TU/asset/solar_energy_v1.1.pdf
Go to page **vii** and click any item from Table of Contents, that item will be aligned exactly at the top of Preview PDF viewer.

Have you tried aligned different paragraphs on the top of viewer annotations?

**Comment by gettalong** [comment]
This PDF works using the XYZ instructions (probably using that because of the two column layout). They also use a GOTO action together with the link instead of directly using a destination. However, both should work fine because the spec allows either one of them to be present.

I have changed your sample code to use the action:

~~~ruby
@pdf.link_annotation(src_rect, A: {Type: :Action, S: :GoTo, D: dest})
~~~

Here is the resulting file, please try it:
[Sample.pdf](https://github.com/prawnpdf/prawn/files/4463609/Sample.pdf)

**Comment by aamir-nazir** [comment]
I have tried the PDF you shared and also tried updated sample code, it's still showing same behaviour, click aligns page top to the PDF viewer top instead of offset provided. It takes to correct page but incorrect offset.

**Comment by aamir-nazir** [comment]
You can try yourself by adding multiple annotations with aligned to the top of each paragraph in the sample.

**Comment by gettalong** [comment]
Hmm... it even works with Adobe Reader 9 (the latest released version for Linux). Have you tried the latest Adobe Reader for macOS?

Do you have a simpler PDF sample with only a handful of pages that works for you?

**Comment by aamir-nazir** [comment]
It's working fine with Adobe Reader for Mac, now it should be a compatibility issue with Preview PDF Viewer Mac. I have tried many PDF files, all of them worked find in Preview.

Here is the simple PDF file with working annotations. I have created this PDF from Google Docs. Seems like they are generating Preview compatible PDF file: https://drive.google.com/file/d/1PXWwVE1wZfsaqCgceZS8Qk-iTpDAClrJ/view?usp=sharing

**Comment by gettalong** [comment]
Thanks for the sample PDF, it also uses the XYZ variant and works everywhere for me. I don't see anything out of the ordinary when inspecting the file.

I have created another test PDF file: [test1.pdf](https://github.com/prawnpdf/prawn/files/4464188/test1.pdf) - does it work in Preview for you?

**Comment by aamir-nazir** [comment]
Yes this worked correctly in Preview, clicking at **`Testing`** aligns specific offset on the top. Please share code sample that you used for creating **test1.pdf**.
Thanks

**Comment by gettalong** [comment]
This file was created with another library, just to see if I can generate something that works for you. Will see what I can do with Prawn.

**Comment by gettalong** [comment]
Here is another, Prawn generated file for you to test: [Sample.pdf](https://github.com/prawnpdf/prawn/files/4464354/Sample.pdf).

**Comment by aamir-nazir** [comment]
It's working perfectly.

**Comment by gettalong** [comment]
I changed two lines in your sample code:

~~~ ruby
dest = @pdf.dest_xyz(0, top_offset, nil, @pdf.state.pages[1])
@pdf.link_annotation(src_rect, Dest: dest)
~~~

So please try that with your main document to see if it works!

Seems that Preview has problems with the FitH destinations...

**Comment by aamir-nazir** [comment]
Perfectly worked! Thanks a lot

**Comment by aamir-nazir** [comment]
It would be more helpful for the readers if we update the documentation for `link_annotation` and `destination` with some examples delineating options supported.

**Comment by gettalong** [comment]
Good idea - would you mind creating a pull request for that?

I think that the issue can be closed now.

**Comment by aamir-nazir** [comment]
Yeah sure, I will draft some documentation updates along with some good examples.
Thanks again.
