### ISSUE TITLE
write text combine two language 

### ISSUE THREAD

**Issue by TalaatMagdy** [prawnpdf/prawn#1156]
i need write text combine two language for example 
use `require 'arabic-letter-connector'`
```
    text_direction :rtl # ltr
    long_text = " Algorithm & Data Structure مرحبا يا العالم"
    text long_text.connect_arabic_letters
```
if use  `text_direction :rtl`  appear correct Arabic word but English appear `A & ataD erutcurtS`

i need combine Arabic and English  for example 
```
Algorithm & Data Structure مرحبا يا العالم
```

I try fonts `Cairo`, `KacstOne`, `Amiri`

My environment 
```
ruby "2.4.2"
gem 'rails', '5.1.4'
# pdf generate
gem 'prawn'
gem 'prawn-table', '~> 0.2.2'
gem 'arabic-letter-connector', '~> 0.1.1'
```

**Comment by gettalong** [comment]
Have you tried separating the Arabic from the English text and printing them separately?

Generally, for this to work correctly one needs to implement Unicode BiDi support. You could try using the [Twitter CLDR](https://github.com/twitter/twitter-cldr-rb#text-segmentation) library. Maybe it also has what's needed for this to work.

**Comment by TalaatMagdy** [comment]
i try from documentation example like 
```
 formatted_text [{ :text => "لعالم".connect_arabic_letters , :direction => :rtl  },
                    { :text => "مرحبا".connect_arabic_letters, :direction => :rtl },
                    { :text => "won't", :direction => :ltr, :size => 24 },
                    { :text => "work", :direction => :ltr },
                    { :text =>
                          "compare" }]
``
appear this `مرحبالعالمwon'tworkcompare` it good Progress but i accept list of words not know arabic or english index like
1-  `['hello', 'world', 'مرحبا','الجميع']`
2-  `['مرحبا', 'world', '','الجميع']`

**Comment by TalaatMagdy** [comment]
i resolve this issue use connect_arabic_letters.reverse . @gettalong thanks
