### ISSUE TITLE
[Documentation] One example for OTF fonts?

### ISSUE THREAD

**Issue by rubyFeedback** [prawnpdf/prawn#1166]
I just read the news about a new release on reddit.

Would it be possible to add an example how to use a OTF font
specifically? Perhaps linked in to from the main README.md
if this is not too much work. Really just some "hello world"
example here but a specific OTF font. (I am more familiar
with TTF fonts so right now I have no idea if there is any
difference between these two.)

Please feel free to close this issue at any moment in time.

**Comment by pointlessone** [comment]
Release notes mention that you use them exactly as you use TTF fonts.

There are no changes to the API. No new methods to use. The only thing that changes is that you can point Prawn to an OTF file and it would understand it.

```ruby
font_families.update(
  'MyOTF' => {
    normal: "fonts/My Fancy OpenType Font.otf"
  }
)

font('MyOTF') do
  text 'This text is rendered with My Fancy OpenType Font'
end
```
