### ISSUE TITLE
Bounding box depth not constrained by the dimensions of its member bounding boxes

### ISSUE THREAD

**Issue by roscom** [prawnpdf/prawn#1177]
Prawn version 2.3.0

I have a situation with a bounding_box of a given width, which contains a number of other bounding_box(es) arranged horizontally, each with different depths. 
The depth of the containing bounding box seems to assume the depth of the last contained bounding_box emitted.
Which is fine, except if the last contained bounding_box has a depth less than any of the other contained bounding_box(es).

**Comment by petergoldstein** [comment]
@roscom I know it's been a while, but any chance you could provide a code snippet to demonstrate the issue?

**Comment by pointlessone** [comment]
This is not mentioned in the documentation but this is how it's currently implemented.

A workaround would be to manually track height of your actual bounding boxes and then adding an empty bounding box with the maximum height of those other boxes.

---

Changing this behaviour seems like a big breaking change. I'm adding it on my list of possible big features and will think about it but for now I'm closing this issue.
