### ISSUE TITLE
adding an image to pdf from just image data

### ISSUE THREAD

**Issue by MyNameIsntBob** [prawnpdf/prawn#1183]
So I have an image that's being saved in a database that I need to show on my Prawn Pdf, but when I pull the image, decode it, and try to display it on the Prawn PDF, I keep getting the issue where it wants a file path. Is there a way that I can pass the image data to the pdf, instead of the a file path, and it can just display that image?

**Comment by MyNameIsntBob** [comment]
Ok, I ended up finding out how to do that. 

`
pdf.image (MiniMagick::Image.read(Base64.decode64(self.signature))).format('jpg').path
`

**Comment by mojavelinux** [comment]
It's a lot simpler than that. The image method requires either a path or an IO object. So all you need to do is create an IO object from your image data and pass that to the image method.

Here's an example (which shows the image being read from a file, but you can replace this with your database record)

```ruby
require 'stringio'

image_data = File.binread 'ruby.png'
image_io = StringIO.new image_data
pdf.image image_io
```

**Comment by pointlessone** [comment]
@mojavelinux Thank you for your answer.

@MyNameIsntBob I believe the issue is resolved. Feel free to reopen if you have more to add.
