### ISSUE TITLE
Problem with interface between prawn and prawn-svg when attempt is made to render a gradient

### ISSUE THREAD

**Issue by mojavelinux** [prawnpdf/prawn#1196]
Since Ruby 3, there appears to be a problem with the interface between prawn and prawn-svg when prawn-svg attempts to render a gradient. It seems to be a result of how keyword arguments are interpreted.

Here's an example of the arguments that prawn-svg sends to `:fill_gradient`:

```
[{:from=>[0.0, 498.80], :to=>[40.0, 458.80], :stops=>[[0.0, "ffffff"], [1.0, "6451a0"]], :apply_transformations=>true}]
```

Here's how the `:parse_gradient_arguments` method in prawn responds:

```
Unknown type of gradient: [{:from=>[0.0, 498.80], :to=>[40.0, 458.80], :stops=>[[0.0, "ffffff"], [1.0, "6451a0"]], :apply_transformations=>true}]
```

Here's a workaround I put in place in Asciidoctor PDF:

```ruby
def parse_gradient_arguments *args, **kwargs
  if args.length == 1 && Hash === (actual_kwargs = args[0]) && kwargs.empty?
    super(**actual_kwargs)
  else
    super
  end
end
```

This is obviously just a quick fix. I'm unsure whether it's prawn or prawn-svg that needs to be updated. I just wanted to make you aware of the problem so we can figure out the right course of action.

cc: @mogest

**Comment by mtasaka** [comment]
This is ruby 3.0 keywod separation change and looks like prawn-svg side needs fixing: https://github.com/mogest/prawn-svg/pull/133

**Comment by mojavelinux** [comment]
Yes, I was able to remove the workaround when I upgraded to praawn-svg 0.32.0. See https://github.com/asciidoctor/asciidoctor-pdf/commit/2ea912c51abdf078034b342e0bff667b31063b2a

**Comment by petergoldstein** [comment]
@pointlessone per @mojavelinux 's last comment, this issue can be closed.
