### ISSUE TITLE
prawn encryption password in section 

### ISSUE THREAD

**Issue by pavanscs** [prawnpdf/prawn#1197]
i am facing a problem with prawn PDF encryption. it is working but when it is opened with a password and i have to reload the section to rise the password security request. what i need is in a same section if i close the file and reopen the pdf again it have to ask for password without reloading the page/ section. can any once has the solution for this problem.

**Comment by pointlessone** [comment]
I suspect your PDF reader is trying to be helpful and remembers the password for you.

You can try watching the encrypted file. I'm pretty sure it's not changed once you enter the password. And if that's the case, how it can be rendered if the file is still encrypted?
