### ISSUE TITLE
Calculating text size issue

### ISSUE THREAD

**Issue by meap** [prawnpdf/prawn#1199]
I have prepared a small demo [here](https://github.com/meap/prawn-wrong-size), which demonstrates the problem with calculating the size of the text and its rendering in the text box.

Can you advise me what's wrong, or if it's a bug in prawn, fix it?

**Comment by gettalong** [comment]
Does this also occur if you are not using a template?

**Comment by meap** [comment]
@gettalong yes

**Comment by gettalong** [comment]
Thanks. Testing this out a bit it seems to only occur if the width set in `render_caption` gets too big. If you reduce it, it will work fine. Due to this I'm guessing this is a bug in Prawn itself but haven't investigated further.

**Comment by gettalong** [comment]
@meap Are you by any chance running Ruby 2.7+? If yes, then the problem appears to be due to a caching issue that is described in #1140 and fixed with #1169 that has already landed in master.

After updating to the master version your small demo works fine.

**Comment by meap** [comment]
@gettalong you're right.
