### ISSUE TITLE
OTF fonts rendering scrambled glyphs or not rendering

### ISSUE THREAD

**Issue by nburdscribe** [prawnpdf/prawn#1203]
### Description of Problem
I'm encountering issues with Type 1C OTF fonts with Prawn 2.4.0 and TTFunk 1.7.0. I was able to replicate these issues using the OTF fonts included in the testing suites for TTFunk and Prawn. I couldn't embed any of the OTF fonts in these libraries without issues.

It seems like there are two kinds of issues I run into when using certain OTF fonts within Prawn to generate PDFs.

1. The glyphs appear totally scrambled in certain environments. A font may look okay in Ubuntu's document viewer and Chrome, but use the wrong glyphs when the same file is opened in Acrobat on Windows or in Firefox.
2. In other cases, the font simply doesn't appear in the finished PDF or has other issues that are independent of the platform.

In both cases, the text copies out of the document correctly. It's just the glyphs that appear to be wrong or missing. I can create PDFs in other programs using these fonts without apparent portability issues, so I don't think it's an issue with the fonts themselves.

### Program to replicate issue
I created a very simple project to replicate the issues. To keep this straightforward, I used the fonts from TTFunk and Prawn libraries. They are placed in the same folder as the Ruby file

```
Prawn::Document.generate('embedded_font.pdf') do
  font_families.update('Exo' => {normal: 'Exo-Regular.otf'})
  font_families.update('AlbertTextBold' => {normal: 'AlbertTextBold.otf'})
  font_families.update('Bodoni-Book' => {normal: 'Bodoni-Book.otf'})
  font_families.update('ComicJens-Regular' => {normal: 'ComicJens-Regular.otf'})
  font_families.update('ColorTestSbix' => {normal: 'ColorTestSbix.ttf'})
  font_families.update('DejaVuSansTTF' => {normal: 'DejaVuSans.ttf'})
  font_families.update('DejaVuSansTTC' => {normal: 'DejaVuSans.ttc'})

  font_size 12
  font 'Exo'
  text 'Hello World'
  font_size 12
  font 'AlbertTextBold'
  text 'Hello World'
  font_size 12
  font 'Bodoni-Book'
  text 'Hello World'
  font_size 12
  font 'ComicJens-Regular'
  text 'Hello World'
  font_size 12
  font 'ColorTestSbix'
  text 'Hello World'
  font_size 12
  font 'DejaVuSansTTF'
  text 'Hello World'
  font_size 12
  font 'DejaVuSansTTC'
  text 'Hello World'
end
```

### Results

-   **Exo:** Looks fine in Ubuntu Document Viewer and Mac Acrobat. Only one letter shows up in Firefox and Windows Acrobat.
-   **AlbertTextBold:** Doesn't show up anywhere. In Windows Acrobat, reports "Cannot extract the embedded font 'da39a3+AlbertText-Bold'. Some characters may not display or print correctly."
-   **Bodoni-Book:** Glyphs look fine in Document Viewer and Mac Acrobat. Glyphs completely scrambled in Firefox and Windows Acrobat. If I change the letters in the source program, different characters will correspond to different glyphs.
-   **ComicJens-regular:** Only one letter shows up, often in the wrong location in Ubuntu. Doesn't appear at all elsewhere.
-   **ColorTestSbix:** Doesn't show up anywhere.
-   **DejaVuSansTTF:** Looks fine everywhere.
-   **DejaVuSansTTC:** Looks fine everywhere.

### Illustrations

Please ignore the mismatches in scale.

PDF opened in Ubuntu Document Viewer.

![font_ubuntu](https://user-images.githubusercontent.com/11034061/114581391-ac2d5900-9c4d-11eb-8383-8cbfb169d662.png)

PDF opened on Mac in Acrobat.

![font_mac_acrobat](https://user-images.githubusercontent.com/11034061/114581479-b8191b00-9c4d-11eb-90f7-796774fa0dd7.png)

PDF opened on PC in Acrobat. Similar results when opened in Firefox within Ubuntu.

![font_pc_acrobat](https://user-images.githubusercontent.com/11034061/114581497-bd766580-9c4d-11eb-9e09-d234c5aa539e.png)

### Questions

Are TTFunk and Prawn supposed to support all OTF subtypes? Or is it only supposed to work with TrueType OTF fonts? I know OTF support within Prawn/TTFunk is relatively recent so I'm uncertain if this is a known limitation or if only certain OTF fonts are supported.

If there's a limitation, is there a way I should be able to identify and flag problematic/unsupported OTF fonts using TTFunk or Prawn? Right now, the only thing that seems obvious is for a person to manually check the output in multiple environments. It would be nice to be able to programmatically identify these in order to provide warnings to the user.

Any help is much appreciated.

**Comment by nburdscribe** [comment]
I've done some digging here and I think there are at least a few overlapping OTF issues between Prawn and TTFunk.

The simplest one I've been able to reproduce is related to AlbertTextBold and ComicJens-regular. These 2 fonts just don't seem to show up unless at least 14 unique glyphs of the font are included in the PDF that you're creating. Is it possible that an attribute of the font is being ignored in favor of some hardcoded value or that some value is being packed incorrectly? It's worth mentioning that even when there are 14 glyphs or more, the fonts are scrambled in certain environments similarly to how Bodoni-Book is scrambled in my original comment.

I get the sense that ColorTestSbix isn't a full font and I shouldn't worry that it's not appearing in this test program.

I've made minimal progress identifying the cause of the two other big related issues I'm seeing with OTF fonts:

- font glyphs appear different in different environments (probably Prawn issue)
- those font glyphs are scrambled in some of those environments (probably TTFunk issue)

However, my very limited progress don't seem to work outside the limited alphanumeric range and a handful of punctuation characters. A lot of my findings on this are fairly speculative. I can summarize my results on this in a follow up comment in case somebody with a better understanding of the font aspect of these libraries reviews this.

**Comment by pointlessone** [comment]
@nburdscribe Thank you for investigating this. Please do share your results. They will definitely help whoever will work on this.

**Comment by nburdscribe** [comment]
Let me know if I can clarify anything or be helpful in any way here. I'd be open to helping with the fixes here if I can.

### Font glyphs appear different in different environments (probably Prawn issue)

Right now, the descriptor embedded by Prawn/Fonts/TTF/embed is hardcoded to follow the expectations for TrueType fonts.

I've altered this on my end to use the settings recommended for 1C fonts by the PDF specification when the font contains a CFF table.

This doesn't solve the problem, but does alter it in an interesting way. Instead of fixing the scrambled letters to be non-scrambled, it makes the OTF fonts appear in the more scrambled way in all environments. My interpretation here is that the different readers were ignoring or paying attention to different pieces of data about the embedded font, but that the altered font descriptor forces the embedded font to be interpreted in a certain way in more environments. This is hard to prove, and it's certainly possible I'm mistaken.

#### Local patch "fix"

```
module Prawn
  module Fonts
    class TTF
      def embed(reference, subset)
        font_content = @subsets[subset].encode

        # FIXME: we need postscript_name and glyph widths from the font
        # subset. Perhaps this could be done by querying the subset,
        # rather than by parsing the font that the subset produces?
        font = TTFunk::File.new(font_content)

        # empirically, it looks like Adobe Reader will not display fonts
        # if their font name is more than 33 bytes long. Strange. But true.
        basename = font.name.postscript_name[0, 33].delete("\0")

        raise NoPostscriptName.new(font: font) if basename.nil?

        is_truetype = !font.cff.exists?

        fontfile = @document.ref!(Length1: font_content.size) if is_truetype
        fontfile = @document.ref!(Subtype: :Type1C) if !is_truetype
        fontfile.stream << font_content
        fontfile.stream.compress!

        descriptor = @document.ref!(
          Type: :FontDescriptor,
          FontName: basename.to_sym,
          FontFile2: fontfile,
          FontBBox: bbox,
          Flags: pdf_flags,
          StemV: stem_v,
          ItalicAngle: italic_angle,
          Ascent: @ascender,
          Descent: @descender,
          CapHeight: cap_height,
          XHeight: x_height
        ) if is_truetype

        descriptor = @document.ref!(
          Type: :FontDescriptor,
          FontName: basename.to_sym,
          FontFile3: fontfile,
          FontBBox: bbox,
          Flags: pdf_flags,
          StemV: stem_v,
          ItalicAngle: italic_angle,
          Ascent: @ascender,
          Descent: @descender,
          CapHeight: cap_height,
          XHeight: x_height
        ) if !is_truetype

        hmtx = font.horizontal_metrics
        widths = font.cmap.tables.first.code_map.map do |gid|
          Integer(hmtx.widths[gid] * scale_factor)
        end[32..-1]

        # It would be nice to have Encoding set for the macroman subsets,
        # and only do a ToUnicode cmap for non-encoded unicode subsets.
        # However, apparently Adobe Reader won't render MacRoman encoded
        # subsets if original font contains unicode characters. (It has to
        # be some flag or something that ttfunk is simply copying over...
        # but I can't figure out which flag that is.)
        #
        # For now, it's simplest to just create a unicode cmap for every font.
        # It offends my inner purist, but it'll do.

        map = @subsets[subset].to_unicode_map

        ranges = [[]]
        map.keys.sort.reduce('') do |_s, code|
          ranges << [] if ranges.last.length >= 100
          unicode = map[code]
          ranges.last << format(
            '<%<code>02x><%<unicode>04x>',
            code: code,
            unicode: unicode
          )
        end

        range_blocks =
          ranges.reduce(+'') do |s, list|
            s << format(
              "%<lenght>d beginbfchar\n%<list>s\nendbfchar\n",
              lenght: list.length,
              list: list.join("\n")
            )
          end

        to_unicode_cmap = UNICODE_CMAP_TEMPLATE % range_blocks.strip

        cmap = @document.ref!({})
        cmap << to_unicode_cmap
        cmap.stream.compress!

        reference.data.update(
          Subtype: :TrueType,
          BaseFont: basename.to_sym,
          FontDescriptor: descriptor,
          FirstChar: 32,
          LastChar: 255,
          Widths: @document.ref!(widths),
          ToUnicode: cmap
        ) if is_truetype

        reference.data.update(
          Subtype: :Type1,
          BaseFont: basename.to_sym,
          FontDescriptor: descriptor,
          FirstChar: 32,
          LastChar: 255,
          Widths: @document.ref!(widths),
          ToUnicode: cmap
        ) if !is_truetype
      end
    end
  end
end
```

### Font glyphs are scrambled in some environments (probably TTFunk issue)

My experiments within TTFunk have been a little more haphazard. I assume that if this goes somewhere, a separate issue needs to be opened in TTFunk, but at the moment the two issues feel tied closely together. I'm able to resolve certain scrambling issues by altering the GID mapping (getting rid of the .notdef mapping, which I don't think should be there), but the font still seems to have troubles outside of a fairly limited ASCII range. Characters that are allegedly part of the Bodoni fonts, for instance, don't appear. Add a curly quote to the "Hello World" text, and it won't appear. I suspect I'm not very close to a full solution here.

In the patch fix below, I am also forcing the charset to be encoded as an array of SIDs instead of as a range. This is to help with troubleshooting. Storing this stuff as a range makes it hard to pinpoint where an issue occurs because it seems to affect the rendering of every glyph with a higher unicode value than the one that disappears.

####  Local patch "fix"

```
module TTFunk
  class Table
    class Cff < TTFunk::Table
      class Charset < TTFunk::SubTable
        def encode(mapping)
          # no offset means no charset was specified (i.e. we're supposed to
          # use a predefined charset) so there's nothing to encode
          return '' unless offset

          sids = mapping.keys.sort.map { |new_gid| sid_for(mapping[new_gid]) }
          sids.delete(0) #.notdef should not be encoded
          ranges = TTFunk::BinUtils.rangify(sids)
          range_max = ranges.map(&:last).max

          range_bytes =
            if range_max.positive?
              (Math.log2(range_max) / 8).floor + 1
            else
              # for cases when there are no sequences at all
              Float::INFINITY
            end

          # calculate whether storing the charset as a series of ranges is
          # more efficient (i.e. takes up less space) vs storing it as an
          # array of SID values
          total_range_size = (2 * ranges.size) + (range_bytes * ranges.size)
          total_array_size = sids.size * element_width(:array_format)

          #if total_array_size <= total_range_size
            ([format_int(:array_format)] + sids).pack('Cn*')
          #else
          #  fmt = range_bytes == 1 ? :range_format8 : :range_format16
          #  element_fmt = element_format(fmt)
          #  result = [format_int(fmt)].pack('C')
          #  ranges.each { |range| result << range.pack(element_fmt) }
          #  result
          #end
        end
      end
    end
  end
end
```

**Comment by adrian-gray** [comment]
Small note to add. I was using OTF fonts which seemed to be working fine. A team member opened one of the PDFs, and the characters were offset by one – 'A' displayed as 'B' and so on. 

I tried it with a few other people. Some had the same issue, some didn't. Not a Mac/Windows issue and not does not seem to be a reader issue.

I converted them to TTF and they worked fine.

**Comment by pointlessone** [comment]
@adrian-gray Could you please provide any specifics? E.g. issue is present on this OS and this renderer (version), not present in this other renderer on this OS, etc.

Also if you can, could you please upload a sample PDF that demonstrates the issue?

**Comment by adrian-gray** [comment]
Sure @pointlessone 

Most of the sample were very non-tech and I'd have to be on their comps to get the details. But I can give one working, and one failing one (it was also failing on a second Mac, working on a third Mac, and working on a seperate iPhone):

Works fine:
OSX 12.2.1 + (Chrome 98.0.4758.102 or Acrobat Pro DC 2021.11.20039.0)

Offset font:
Windows 10 Pro 21H1 + Acrobat Reader DC 2021.011.20039

Example link: 
[https://www.dropbox.com/s/2d1fcfonjaa6341/AS%20Child.pdf?dl=0](https://www.dropbox.com/s/2d1fcfonjaa6341/AS%20Child.pdf?dl=0)

**Comment by pointlessone** [comment]
@nburdscribe @adrian-gray Could you please try master branches of Prawn, pdf-core, and TTFunk and let me know if the issue is still there?

**Comment by pointlessone** [comment]
I'll assume the issue has been resolved.

Feel free to reopen with more details.
