### ISSUE TITLE
Adding .encoding method to Prawn::Document ?

### ISSUE THREAD

**Issue by rubyFeedback** [prawnpdf/prawn#1216]
pdf = Prawn::Document.new(
            page_size: 'A4',
            page_layout: :landscape
          )

    pdf.encoding

Would it be possible to support the latter?

I can do so on a String object in ruby.

Reason I am asking is because I have a UTF-8 string, from a file,
but prawn does not want me to render it into the pdf file via
.text(). It says something about windows incompatibility. This is
a bit confusing ... I'd love for Prawn::Document to tell me which
encoding it uses via .encoding though.

**Comment by pointlessone** [comment]
`Prawn::Document` doesn't have an encoding.

The message you get is not about the document encoding. It's about fonts. PDF has a bunch of built-in fonts but they only support very limited set of characters they can display. When Prawn gets a UTF-8 string it can not properly render it with those fonts. To overcome this you have to give Prawn an external TTF/OTF font.
