### ISSUE TITLE
`width_of` not considering linebreaks

### ISSUE THREAD

**Issue by estani** [prawnpdf/prawn#1218]
When then content send to `width_of` has a line-break, the sum of all lines is returned, instead of the maximal:

```ruby
content_a = "x"
content_b = "x\nx"

puts "#{content_a}: #{width_of(content_a)}" # x: 5.33
puts "#{content_b}: #{width_of(content_b)}" # x
                                            # x:10.66
```
The width of `content_b` should be clearly the same of `content_a` as only the height or length changed.

**Workaround**:
```ruby
real_width = content.gsub('<br>', "\n").split("\n").map { |line| width_of(line) }.max
```

**Comment by gettalong** [comment]
Are you using `#width_of` directly or via another method?

If it is the former, I guess the method works as expected based on the following comment inside of it: *Build up an Arranger with the entire string on one line, finalize it, and find its width.*

If it is the later, could you provide a real world example where this is a problem?

**Comment by estani** [comment]
Indeed that's the method, but at least in the example I've provided that's not the branch being called, as I haven't provided the `inline_format` option
https://github.com/prawnpdf/prawn/blob/0c64cd47c52a3344e5a0efff360c0711fee4091d/lib/prawn/font.rb#L131-L146

Even if that where the case, I hardly believe removing the `<br>` and computing a width that is not that of the line would have been the intention of that code line. But I agree that that's more difficult, as every part of the text need to be formatted before being measured, etc. (unless the arranger already does that, haven't checked)

In any case, I'm referring to this line:
https://github.com/prawnpdf/prawn/blob/0c64cd47c52a3344e5a0efff360c0711fee4091d/lib/prawn/font.rb#L144
Which ends up calling:
https://github.com/prawnpdf/prawn/blob/0c64cd47c52a3344e5a0efff360c0711fee4091d/lib/prawn/fonts/ttf.rb#L64
And the algorithm there just sums all characters _as if_ they were on a line. In case of a liner break in the string this is just wrong.

The real world example is exactly like the example I gave, only that the content is unknown.
We need to compute the width of the line to use it in prawn_table, but that's out of the current repository.
Just for completion sake: we measure the line width of every cell in a table, get the maximum of the column, and use it to define how large the column-width should be.

**Comment by gettalong** [comment]
Yes, I know that the comment is in the `if` section. However, it doesn't make sense from an API point view to do different things for normal strings and inline formatted strings. Therefore I gather that it is always meant to just be the width of the input string, disregarding any line breaks.

I agree that the code *could* respect the newline character. But where do we stop here? How would you handle, for example, a tab character?

The `#compute_width_of` method does the simplest thing possible, deferring the more complicated stuff to the caller. So what you titled work-around is actually the expected way to handle such things.

FYI: Be aware though that this is just my interpretation of the code when taking into account how fonts/glyphs work in PDF.

**Comment by estani** [comment]
Good points, but if the tab is indeed rendered, then it takes place and increases the width.

I don't really think it's that complicated, only line breaks "reset" the width, and the with of the string, is just the width of the longest line.

Same thing with the height, if it would be computed, which without giving any more info would result in just `content.split("\n").length * line_height + (content.split("\n").length. - 1) * interline_spacing`

I don't see the point of not returning the width of the line, specially if it's possible (see workaround). Returning instead the width of a different string (i.e. one with the line breaks removed) is somehow strange in my opinion.

In any case, the work around here helps documenting this shortcoming in case someone wants to use the method, and cannot assure there will never be a line break in it.

**Comment by gettalong** [comment]
Maybe the initial reason for the method was just to provide the simplest possible implementation.

> I don't see the point of not returning the width of the line, specially if it's possible (see workaround). Returning instead the width of a different string (i.e. one with the line breaks removed) is somehow strange in my opinion.

Note that **any characters** for which no glyph exist are removed

Just for comparison: In HexaPDF any string that should be rendered is turned into an array of glyph objects. This initial transformation also means that this array can only contain valid glyphs, all invalid (=non-existant) glyphs like one for a line break are represented by a special invalid glyph class. All operations like getting the width/height is then performed on that array.  If an array with an invalid glyph makes it to the lowest level text rendering method, an error is raised. This means that all such special characters like line breaks must be handled by higher-level code in a way it sees fit.

**Comment by gettalong** [comment]
I will close the issue because I don't think that the implementation will be changed.

**Comment by estani** [comment]
ok, just for completion sake, as your statement "Note that any characters for which no glyph exist are removed" is not correct, here the proof:

```ruby
width_of("x")   # 5.33
width_of("x ")  # 8.74
width_of("x\t") # 10.33

width_of(" ")   # 3.41
width_of("\t")  # 5.0
width_of(" \t") # 8.41

# and this is what I say is wrong
width_of(" \n\t") # 8.41

# expected would be:
# width_of(" \n\t") -> 5.0 as [width_of(" "), width_of("\t")].max 
```

**Comment by pointlessone** [comment]
You assume there's a thing called "tab stop". It's probably a valid assumption, after all you see it everywhere: terminals, word processors, etc. But it's not the case in Prawn. Prawn uses default advance values provided by the font. There's no way to define tab stops for text rendering in Prawn. You'll have to handle that manually.

**Comment by estani** [comment]
That wasn't the idea of the previous entry. The tab was just to show that Prawn defines a width for it, just as for a space (to correct the previous assumption that it does not). By the way that's not a tab stop, is just a 5 point width, a tab stop would behave differently (i.e. `"\t".width == " \t".width`)

**Comment by pointlessone** [comment]
Prawn doesn't define the width of tab character. The font does. There's a glyph in the font that corresponds to the tab character. That glyph most likely has no graphic component to it but it has what's called Advance Width. That number specifies for how much to move the graphic cursor after rendering a glyph. Incidentally, that's what Prawn uses to determine width of a character.
