### ISSUE TITLE
Masks are not really transparent?

### ISSUE THREAD

**Issue by brandoncc** [prawnpdf/prawn#1219]
I'm trying to create an image like this:

![masks](https://user-images.githubusercontent.com/543973/132638896-1a00a9da-b020-4413-bdcf-2c2244966371.png)

with the following code:

```ruby
require 'prawn'
require 'prawn-svg'
require 'vips'

page_height = 500
page_width = 500

Prawn::Document.generate('masks.pdf', page_size: [page_height, page_width], margin: 0) do
  save_graphics_state do
    soft_mask do
      fill_color 0, 0, 0, 0
      fill_rectangle [0, page_height], page_width, page_height

      fill_color 0, 0, 0, 100
      fill_rounded_rectangle [100, page_height - 100], page_width - 200, page_height - 200, 20
    end

    fill_color 'ff0000'
    fill_rectangle [0, page_height], page_width, page_height
  end
end

image = Vips::Image.pdfload('masks.pdf')
image.write_to_file('masks.png')
```

but the code produces this instead:

![masks](https://user-images.githubusercontent.com/543973/132638515-5af3ed5d-1417-4af3-9eb8-dfd020637dca.png)

Neither my masks.pdf nor masks.png files seem to actually contain transparent centers. Am I doing something wrong? I need to be able to use the image as a "frame" to place as a layer over top of other content on a website, so the center has to be transparent.

Thank you!

**Comment by gettalong** [comment]
Try using RGB colors instead of CMYK, i.e. `fill_color "FFFFFF"` and `fill_color "000000"` inside the soft mask block. This seems to produce the correct result.

**Comment by brandoncc** [comment]
Thank you! I actually had two issues. The slight red tint due to CMYK, and the non-transparent PDF background. For the latter I had to add `background: 0` to my `#pdfload` call. That is unrelated to prawn, but is relevant to the code I pasted so providing the solution here in case anyone stumbles across the code and tries to use it.
