### ISSUE TITLE
Text and images sometimes on the wrong page

### ISSUE THREAD

**Issue by Bodata** [prawnpdf/prawn#1222]
Hi,
I have problem when i generate a pdf file things seem to get mixed up.

(I use prawn 2.4.0 and prawn-table 0.2.2)

In development the report with a variable number of pages works ok.
In production (Heroku) i get sometimes wrong text and images from other pages on the first page.
Intended tekst on the first pages seems to be starting lower.

My code is quite complex but the flow is like below:

```
 @pdf = Prawn::Document.new
 #Put out header and table
 # loop for number of pages
  @pdf.start_new_page
  # put out header text table and images
```
Now i get sometimes an image and some text on the first page ? 

Problem is i cannot reproduce the problem, if i run the report a second time the report is ok.
Should i initialize some variables ?

Regards,
Peter

**Comment by pointlessone** [comment]
No, you don't need to explicitly initialize any variables.

I suspect the code you presented is not quite representative of your actual code. Maybe your `@pdf` gets mixed up with something or is a leftover from previous call?

Try `Prawn::Document.generate` with a block and see if that fixes your issue. Other than that it's hard to recommend anything without a representative code example.
