### ISSUE TITLE
how to set cursor at every new page?

### ISSUE THREAD

**Issue by buncis** [prawnpdf/prawn#1226]
I've tried to use 

```
on_page_create do 
  set_cursor_to 650
end
```

or 

```
repeat(:all) do 
  set_cursor_to 650
end
```

still the context from last page just flowing at the `bounds.top.left` which is 726

I should use discussions thread instead opening this issue sorry

**Comment by gettalong** [comment]
There is no method `#set_cursor_to` in prawn or pdf-core. I suggest using the `top_margin` option when creating a document to set another top margin that suits your use-case.
