### ISSUE TITLE
Issue in using partial pdf prints

### ISSUE THREAD

**Issue by kamalpanhwar** [prawnpdf/prawn#1232]
We have been using Prawn from 2016, and all our reports working fine. Recently we noticed our report has some character not printing correctly. As we have not change anything on the code side. So I downgrade prawn to `gem 'prawn', '2.1.0' and it is working fine. but later version it does not work correctly and add weird characters.
Result coming in version 2.1.0

![image](http://mailtrap.xyz/images/correct_image.png)

Where in latest version it prints like following

![image](http://mailtrap.xyz/images/wrong_image.png)

Issue only happen when we merge document, if print individually it works fine. So seem when we use it partial.

**Comment by gettalong** [comment]
* What do you mean by "merging documents"?

* Can you provide example documents? E.g. the same document once rendered with 2.1.0 and once with the current version?

**Comment by kamalpanhwar** [comment]
Merging mean I have few classes which print few reports separately. Then we have one class which uses all these classes together to create one report. So if I print those separate reports they are coming correctly. But when I print them together using another class. It does not work. 

Our project is very large I will create sample project to reproduce this error.

**Comment by gettalong** [comment]
Ah, thanks for the explanation. Then I'll wait for the executable script.

**Comment by kamalpanhwar** [comment]
We have revert back to 2 version older Gem, and it fixed issue. as I could not create minimal project to show this issue. Will try in future if could find minimal representation of issue, will definitely share you. But my senior told me it is already fixed in PR but they are not merged yet. so I am closing this issue.
