### ISSUE TITLE
Few Currency symbols are not supporting

### ISSUE THREAD

**Issue by bantinarvariya** [prawnpdf/prawn#1257]
Currency symbol like Indian rupee is not supporting at the time of generation of PDF.

Prawn::Document.generate("hello.pdf") do
  text "Grand Total: ₹1000"
end

it support dollar and other few currencies symbols but not supporting rupee currency symbol

**Comment by gettalong** [comment]
You need to use an OpenType font that supports the currency symbols you need. The builtin fonts have a very limited range of supported glyphs.

**Comment by gettalong** [comment]
@bantinarvariya I will close this since there is nothing we can do on our side.
