### ISSUE TITLE
Incompatibility with ruby 3.1

### ISSUE THREAD

**Issue by waghanza** [prawnpdf/prawn#1303]
Hi @pointlessone,

I can see in https://github.com/prawnpdf/prawn/blob/8ceaa105f3e6038fac2eb4b84355d71b00d895f3/prawn.gemspec#L39 that `prawn` require **matrix**.

However, this line is not in `2.4.0`, and then this version could not be used with ruby **3.1**+.

May a new version be published ?

Regards,

PS : `matrix` has been removed => https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/

**Comment by gettalong** [comment]
See https://github.com/prawnpdf/prawn/issues/1273
