### ISSUE TITLE
Error in the manual? (page 11)

### ISSUE THREAD

**Issue by bgvo** [prawnpdf/prawn#1307]
In page 11 is said:

```
... By defining your own document method, as shown in the example, you will be able...
```

But in the example, such a method (`document`) is not defined. 

<img width="784" alt="image" src="https://github.com/prawnpdf/prawn/assets/3684835/83beba77-b24f-4e0a-999c-d6103157df69">

**Comment by pointlessone** [comment]
You're quite correct. This is a bug.

You can find an example of the method in #1258.

**Comment by pointlessone** [comment]
This has been [fixed](https://github.com/prawnpdf/prawn/blob/1d4469d5b6df09fe417f9adb60070cee2b5195c2/manual/basic_concepts/view.rb#L40-L42). Thank you for bringing my attention to it.
