### ISSUE TITLE
Font cannot be set before first page is created

### ISSUE THREAD

**Issue by westonganger** [prawnpdf/prawn#1369]
If you try to call `font("some-custom-font")` before the first page has been created then you receive a `Prawn::Errors::NotOnPage`

https://github.com/prawnpdf/prawn/blob/c531f87e8cedda95afffbe6207e5c6f3a2de7609/lib/prawn/font.rb#L56-L61

Is there a particular reason for this? Seems to me it should be permissible to switch fonts before creating the first page?

**Comment by gettalong** [comment]
It would be possible to store the font in another way but then more logic would be needed throughout the code.

The reason for this is that before any text can be output, the font needs to be set. So if the font is just stored and not set on the page's state store, it would need to be set (or checked) before every invocation related to text.

Therefore it is much easier to set the font when the method is invoked. And for this the page needs to be available. The same behaviour is used for other methods that set state, e.g. font color, letter spacing, line width...
