### ISSUE TITLE
Table cells that are too tall to fit on one page get truncated; should continue cell contents on next page

### ISSUE THREAD

**Issue by TylerRick** [prawnpdf/prawn#147]
Here's an example showing this issue:

```
Prawn::Document.generate(filename = File.basename(__FILE__) + ".pdf") do
  line_count = 80
  table([
    ["Shorter cell", "Column 2"],
    [(0...line_count).map{|i| "This is line #{i} of #{line_count}\n"}.join, "Column 2"],
    ["Shorter cell", "Column 2"],
  ])
end
```

I believe the expected/desired behavior would to have all content displayed, no matter how many page breaks are required to do so.

Also, I don't think we'd want a bottom border on the first page (or a top border on last page), since we want it to be clear that the cell is continued on the next page.

**Comment by rusllonrails** [comment]
Still getting this error with Rails '4.2.7.1', prawn (1.3.0) and prawn-table (0.2.1).
Any success on fixing it?

**Comment by kashifnaseer** [comment]
any update on this ?

**Comment by melcher** [comment]
Successor to this ticket is https://github.com/prawnpdf/prawn-table/issues/41
