### ISSUE TITLE
make_cell with :borders property doesn't overrides the Table :cell_style{:borders}

### ISSUE THREAD

**Issue by espinosa** [prawnpdf/prawn#289]
Hi,

I wan't to have borders only on 1 cell.

So I remove :borders at the table level (:cell_style) and create a cell with the :borders property.

But in the pdf, there are no borders on the cell.

source:
`
table [['A', make_cell('B', :borders=>[:top, :right, :bottom, :left])], ['A1', 'B1']], :cell_style=>{ :borders=>[] }
`

If I use this syntax, it's ok
`
pdf.table [['A', 'B'], ['A1', 'B1']], :cell_style=>{ :borders=>[] } do |t|
  t.cells[1,1].borders = [:top, :right, :bottom, :left]
end
`

The problem is that the :borders property on the cell doesn't overrides the cells properties defined on the table level.

Regards,

**Comment by estani** [comment]
If anyone has another workaround please share.

We are creating rows dynamically, and grouping them. The cell itself knows where to build the border, but the table does not know where those cells are located. 
The work around we use is to store this information out-of-bound (counting cells in some middle-class to count the rows and use the solution like it was used above)... which is not very nice...

If we could add a payload to the cell, we can find them using a filter or such, but as far as I can see, it is not possible.
Any Ideas would be welcome!
