### ISSUE TITLE
Last line is not rendered

### ISSUE THREAD

**Issue by gioele** [prawnpdf/prawn#318]
The code in https://gist.github.com/1615898 (reduced from https://github.com/gioele/papersize/blob/master/gen-papersize-pdf.rb) will produce a PDF in which the last line generated with `pdf.line` will not be rendered.

Lines are generated with in a loop with

```
bb = pdf.bounds
v_center = pdf.cursor + 0.8.mm

pdf.line [bb.left, v_center], [bb.right, v_center]
```

The bounds are changed in the initial part of the loop, so each line is positioned in a different spot. This code works flawlessly for all the different bounding boxes except for the last. In you uncomment the "B5" line in the gist, the generated code will render all the lines (including the one not shown precedently) but not the B5 line, that now happens to be the last one.

**Comment by westonganger** [comment]
I am experiencing the issue. @yob can you explain to me when I should use pdf.stroke_line instead of pdf.line. What is the difference between the two?

**Comment by cheba** [comment]
@westonganger `line` only creates an abstract graphical object (a line in this case) but you still have to apply some rendering operation to it (like stroke or fill).

`stroke_line` does that for you. It's essentially a sequence like this:
```ruby
pdf.line from, to
pdf.stroke
```

**Comment by westonganger** [comment]
I've only been using `line` and its been rendering fine unless its the odd case.

**Comment by cheba** [comment]
@westonganger PDF has a thing called graphics stream. It's essentially a list of commands a renderer must perform to get the image of your document. It's very granular and has a cumulative effect. A command that produces a line doesn't actually draws it. It just say "a line from here to here". You have to execute another command to make it actually visible. Like a "stroke" command.

Line is a part of Path Construction family of commands. They all get accumulated until a Path Painting command is executed. So when you use `line` you only construct a path. Eventually something else can produce a painting command and that will all so paint the lines.

If you want to know more you can read Graphics Objects section of the latest PDF spec.

**Comment by gioele** [comment]
@cheba thank you for the explanation.

**Comment by westonganger** [comment]
Great I'm glad I got that explained.  Thanks

**Comment by ugifractal** [comment]
thanks.. working
