### ISSUE TITLE
"image file is an unrecognised format" when using open(image-url)

### ISSUE THREAD

**Issue by jaybrueder** [prawnpdf/prawn#334]
Hi!

I want to include a background image to all pages of a certain pdf. 
This image is stored on an external source.
Therefore I use 

This actually works if the pdf is not longer than a single page. As soon as i have multiple pages in this pdf i get the following error message and the pdf doesn't render:

> image file is an unrecognised format

It works perfectly if I don't use open(image-url). But the image needs to be remote, so having the image somewhere in the "public" directory of my Rails App is not an option.

Here is my code

invoices_controller.rb

``` ruby
def show
    @invoice = Invoice.find(:id)

    respond_to do |format|
      format.html
      format.pdf do
        pdf = InvoicePdf.new(@invoice, view_context)
                   send_data pdf.render, filename: "Invoice_#{@invoice.number}.pdf", type: "application/pdf"
      end
    end
 end
```

invoice_pdf.rb

``` ruby
class InvoicePdf < Prawn::Document

def initialize(invoice, view)
    super(margin: [100, 30, 100, 30], page_size: "A4", background: open("#{invoice.background_url}"))

    #Content of PDF
end
```

Edit: My prawn-gem version is "1.0.0.rc1". But it is also not working with any of the older ones.

**Comment by ranganayakulu** [comment]
Unable to use Image URL: 

![Screenshot 2022-08-13 at 6 02 59 PM](https://user-images.githubusercontent.com/13967035/184494205-f1cdd18b-773c-4232-8001-d61e7bb67654.png)


prawn gem version: `gem 'prawn', '~> 2.4'`

`def logo
    image open("https://cdn-icons-png.flaticon.com/512/415/415682.png")
 end`
 
 Thanks in Advance.

**Comment by pointlessone** [comment]
@ranganayakulu Your issue is unrelated to the originally reported one.

Your issue is literally what it says: it can not find a file you gave it in your local filesystem.

To teach `open` understand URLs you need to `require "open-uri"`.
