### ISSUE TITLE
colspan

### ISSUE THREAD

**Issue by cpanderson** [prawnpdf/prawn#335]
I've looked all over and am having trouble using :colspan. I've got the 1.0 RC and I keep getting...

NoMethodError (undefined method `colspan=' for #Prawn::Table::Cell::Text:0x109a1e0a0)

I've been trying to use it like in the documentation...

table = [
  [{:content => "blah", :colspan => 2}],
  ["col1", "col2"]
]

I'm obviously doing something wrong. I've also checked the current issues and I see it implemented like...

table = [
  [{content: "blah", colspan:2}],
]

...but that obviously is syntactally wrong. 

So confused!

Thanks,

Chris

**Comment by Cutta** [comment]
+1

**Comment by sandal** [comment]
This feature exists in prawn-table, and in the 1.x versions of Prawn before we extracted the gem.
