### ISSUE TITLE
Stack Level too deep

### ISSUE THREAD

**Issue by gauravsaini23** [prawnpdf/prawn#345]
Hi ,

I am getting the error 'Stack level too deep' error while generating the pdf without any error trace .

here is the code which is generating the error 
1.      pdf.bounding_box [@document_margin, @document_height - @document_margin], :width => (@content_width - @logo_width - 10), :height => @document_header_height do
2.        pdf.text store_name , :size => (@font_size \* 1.5).to_i, :style => :bold
3.        pdf.text "abc", :size => (@font_size \* 1.2).to_i
4.        pdf.text "#{Time.now}", :size => (@font_size \* 0.8).to_i
5.      end

There is no error if I remove any one of lines from 2, 3, 4 or if store_name is shortened to a length less than 43.

Any guesses or pointers will be helpful ..

**Comment by dm3627** [comment]
hi
