### ISSUE TITLE
How to wrap text around an image?

### ISSUE THREAD

**Issue by fillman** [prawnpdf/prawn#367]
Simple example: image float to the left, text float to the left. Result should be Image and Text starts on the same line and then text wraps an image around (if there's too much text). Is it possible to do it like in beautiful HTML way?

**Comment by tab** [comment]
@practicingruby, I need to do something similar to your screenshot, but link you gave is not currently working.

**Comment by Yahkal** [comment]
you could try this: https://jsfiddle.net/tom613/4o1g03og/

**Comment by DevHachi** [comment]
Any news to that feature. Would be great to have it. :)
