### ISSUE TITLE
Concat a complete PDF file to the current document

### ISSUE THREAD

**Issue by samant** [prawnpdf/prawn#376]
A new method added to document class in order to concatenate a complete existing PDF file to the current edited document.

``` ruby
    #  Concat a PDF files at the end of the existing document
    #
    #  pdf.concat("foo.pdf")
    #
    def concat(pdf_file)
      if File.exists?(pdf_file)
        pdf_temp_nb_pages = Prawn::Document.new(:template => pdf_file).page_count
        (1..pdf_temp_nb_pages).each do |i|
          self.start_new_page(:template => pdf_file, :template_page => i)
        end
      end
    end
```

See this commit:  cf8dfca98e352a958b2ba1b13af3288758e96617

**Comment by akidon** [comment]
start_new_page with template not working :( its getting blank PDF page. Maybe its working without template please help me :+1:

**Comment by packetmonkey** [comment]
@akidon templates where removed from Prawn because the implementation could corrupt PDFs. The source code for that has been moved to https://github.com/prawnpdf/prawn-templates It's mostly unsupported but it may help you out if your use case is simple enough.
