### ISSUE TITLE
Prawn fails on certain PDF templates in lib/prawn/document.rb - generate_margin_box 

### ISSUE THREAD

**Issue by patsch** [prawnpdf/prawn#431]
I am using prawn 0.12.0 to apply a "stamp" to an existing PDF using the "template" mechanism to put the existing PDF in the background using

pdf = Prawn::Document.new(:template => template_path)

This line starts the process - and it fails for certain PDF files.

I have referenced two files:

good.pdf -> http://www.skex.com.au/prawn/good.pdf
bad.pdf -> http://www.skex.com.au/prawn/bad.pdf

that can be used to reproduce the problem (they're the templates I use for testing).

The root cause seems to be that with the bad.pdf template file at this point here in lib/prawn/document.rb around line 664

 def generate_margin_box
      old_margin_box = @margin_box
      page           = state.page
      @margin_box = BoundingBox.new(
        self,
        nil,  # margin box has no parent
        [ page.margins[:left], page.dimensions[-1] - page.margins[:top] ] ,
        :width => page.dimensions[-2] - (page.margins[:left] + page.margins[:right]),
        :height => page.dimensions[-1] - (page.margins[:top] + page.margins[:bottom])
      )

the page.dimensions attribute is an Array for the "good" PDF ([0.0, 0.0, 203.0, 223.0]), whereas for the "bad" pdf it's actually an object of type Prawn::Core::Reference (8 0 R) - which then leads to an error when an attempt is made to use the [] operator on it.

**Comment by wkirby** [comment]
I realize this issue is crazy old, but I still see this problem on 2.2.2 with some PDFs.

**Comment by wkirby** [comment]
Just following up, the core issue is actually on `prawn-templates`, and is solved by this open PR: https://github.com/prawnpdf/prawn-templates/pull/22
