### ISSUE TITLE
Links inside a repeater not working

### ISSUE THREAD

**Issue by jlduran** [prawnpdf/prawn#498]
I don't think this should be the normal behavior, but:

```ruby
repeat :all do
  text "<link href='http://example.com'>external link</link>", inline_format: true
end
```

produces a PDF with no link.

The `/URI (http://example.com)` is there, however, does not work.

**Comment by sandal** [comment]
I've confirmed that #801 is a direct reproduction of this problem at the stamp level, so please follow that ticket for future updates.
