### ISSUE TITLE
Tables: rowspan greater than one-page causes rendering error

### ISSUE THREAD

**Issue by johnnyshields** [prawnpdf/prawn#562]
If a prawn table spans multiple pages (e.g. has 100 rows), and a given cell has a rowspan value greater than the equivalent of 1 page, a glitched layout results.

**Comment by martijn10kb** [comment]
So.. ..anyway.. ..anyone planning on fixxing this? 🙃

**Comment by johnnyshields** [comment]
@martijn10kb the issue is moved to [prawnpdf/prawn-table#3](https://github.com/prawnpdf/prawn-table/issues/3), but it's still not resolved :(

**Comment by martijn10kb** [comment]
@johnnyshields Yeah I saw, and there even was a PR that never is merged.. ..but [prawnpdf/prawn-table](https://github.com/prawnpdf/prawn-table) doesn't seem to be relevant anymore and it looks like it is moved back at some point. ..but I might be wrong haven't invested to much time in this.
