### ISSUE TITLE
Prawn should supports gif images

### ISSUE THREAD

**Issue by prakashsejwani** [prawnpdf/prawn#62]
Prawn supports jpg  and png images to get embbeded on pdf it would be nice if it supports gif images too.

**Comment by haslo** [comment]
Nobody uses GIF anyway.

**Comment by haslo** [comment]
On a slightly more constructive note, for all the others finding this issue when they have GIFs that won't process, here's a quick way to get a PNG with GraphicsMagick if you have a GIF image:

```ruby
img = GraphicsMagick::Image.new(gif_path)
png_path = gif_path.gsub(/\.gif\Z/i, '.png')
img.write(png_path)
```

In our case, the image comes from a user upload and we're using GraphicsMagick already anyway. YMMV.
