### ISSUE TITLE
Relicense under the MIT license

### ISSUE THREAD

**Issue by pointlessone** [prawnpdf/prawn#625]
**FIXME: The list below is incomplete and possibly out of date. [See this comment](https://github.com/prawnpdf/prawn/issues/625#issuecomment-36773203) for details**

Prawn followed Ruby licensing strategy from the very beginning. The main reason for that was that if people can use Ruby in their project they certainly would be able to use Prawn as well. Ruby gave switched grom GPL2/3 to 2-clause BSD license about three years ago.

At this time the most popular license among Ruby projects is [MIT](http://choosealicense.com/licenses/mit/).

The following people's code is in the master right now.
- [x] @aayushkhandelwal11
- [x] @aguids
- [x] @alexdowad
- [x] @astjohn
- [x] @backspace
- [x] @basvk
- [ ] @bluejade
- [x] @boutil
- [x] @bradediger
- [x] @burisu
- [ ] @capps
- [x] @cbartlett
- [x] @cheba
- [x] @crazymykl
- [x] @dougjohnston
- [x] @fidothe
- [x] @FloWi
- [ ] @fnando
- [x] @geeksam
- [x] @gettalong
- [x] @giuseb
- [x] @hbrandl
- [x] @henrik
- [x] @huerlisi
- [x] @igorbozato
- [x] @ivantsepp
- [x] @jamis
- [x] @JEG2
- [x] @jeremyf
- [x] @joncanady
- [x] @joneslee85
- [ ] @jonsgreen
- [x] @jordanbyron
- [x] @jweathers777
- [x] @kennethkalmer
- [x] @koriroys
- [x] @kuroneko
- [x] @lawso017
- [x] @lenny
- [ ] @luis-ca
- [x] @matthewrudy
- [x] @mbklein
- [x] @mdaines
- [x] @mikel
- [x] @mrkn
- [x] @murrekatt
- [x] @nathancolgate
- [x] @p8
- [x] @packetmonkey
- [x] @phurley
- [x] @proactive
- [x] @pwnall / @costan
- [x] @ratbeard
- [ ] @riopro
- [x] @rivsc
- [x] @rubyredrick
- [x] @sandal
- [x] @scoopr
- [x] @scpike
- [x] @seebs
- [ ] @sgwanlee
- [x] @shanebonham
- [x] @sigmike
- [x] @sos4nt
- [x] @strzibny
- [x] @tim-vandecasteele
- [ ] @toretore
- [x] @torgoton
- [x] @trym
- [x] @vizjerai
- [x] @vongrippen
- [x] @weimeng
- [x] @wesgarrison
- [x] @whoops
- [x] @willbryant
- [x] @wpiekutowski
- [x] @yob
- [ ] Jaron Kennel
- [ ] otavio
- [ ] paul

Please chime in below if you object to the move.

**Comment by pjmartorell** [comment]
@practicingruby Any update on this? have you plans to move to MIT license in the near future?
Thanks

**Comment by riopro** [comment]
No, we don't use Ruby any more.
Truly,
Rogério T. Sampaio


21-2524.1077; 21-2262.6246

Conteúdo confidencial. Se a mensagem foi recebida por engano, por favor,
avise ao remetente e apague-a do computador.

Privileged and confidential. If this message has been received in error,
please notify the sender and delete it  immediately.


Em qua., 6 de nov. de 2019 às 09:23, Pere Joan Martorell <
notifications@github.com> escreveu:

**Comment by pointlessone** [comment]
@pjmartorell Gregory doesn't maintain Prawn and is not involved in development any more. Please let him be.

As for the relicensing, it most likely won't happen. Definitely not in the near future. Mostly for logistics reasons. As you can see, it's really hard to definitively identify all the contributors.

**Comment by pointlessone** [comment]
@riopro I'm not sure how to take your response. Could you please clarify? Regardless whether you use Ruby or not you still own the copyright to your contributions and you decide how to license it.

**Comment by johnnyshields** [comment]
It would seem reasonable to me to notify all parties of the change and give everyone a 30-day window to object. Emails are pretty easy to google or find on Github. If no objections, release future versions under the MIT license.

(I am a contributor and I accept the change)

**Comment by pointlessone** [comment]
@johnnyshields It's an OK method of reaching group decisions but doesn't work with IP/copyright. You can't call dibs on someones property if they don't reply in 30 days. You probably can assume they don't care to reply but that doesn't grant you any rights.

**Comment by riopro** [comment]
Sorry, I think I answered without knowing what was the problem, so I was
misunderstood. The fact is that the participants of this project are no
longer working here, and we don't use Ruby anymore. So, we know nothing
about this copyright, so that we accept anything the group think is better.
We don't want to cause any problem.
Atenciosamente,
Rogério T. Sampaio


21-2524.1077; 21-2262.6246

Conteúdo confidencial. Se a mensagem foi recebida por engano, por favor,
avise ao remetente e apague-a do computador.

Privileged and confidential. If this message has been received in error,
please notify the sender and delete it  immediately.


Em qua., 6 de nov. de 2019 às 11:22, Alexander Mankuta <
notifications@github.com> escreveu:

**Comment by strzibny** [comment]
This is good to go from me and I would even say I prefer it.

**Comment by johnnyshields** [comment]
@pointlessone under most legal systems you can call dibs on unclaimed property after some time period.
