### ISSUE TITLE
Fail CI if manual fails to build

### ISSUE THREAD

**Issue by practicingruby** [prawnpdf/prawn#681]

**Comment by tlynam** [comment]
Hi @packetmonkey, I see how we could add the task in travis.yml with `script` or `before_script`
https://docs.travis-ci.com/user/customizing-the-build/#Breaking-the-Build

Sorry, can you please explain how you'd use eval?  What if we wrapped the code within the manual task in a begin rescue block and exited with 1?

**Comment by practicingruby** [comment]
@tlynam: It looks like @packetmonkey's comment was written long before we moved the code for manual generation into its own gem, but this is the method he was referring to:

https://github.com/prawnpdf/prawn-manual_builder/blob/master/lib/prawn/manual_builder/example.rb#L227

I think adding the `begin/rescue` block with an `exit 1` might work there... although we need to think a little bit about whether that's the behavior we actually want, because it means a single exception in the manual on one page would prevent the whole manual from being generated.

But in any case, we could probably add a configurable option which gets set by the tests like `Prawn::ManualBuilder..exit_on_exception = true`, or something along those lines.

Although I'm offically "retired" from Prawn, feel free to follow up from me if you need help with this, and I can perhaps get you set up with a starting point.

**Comment by tlynam** [comment]
Thanks @practicingruby, I'll play around with it and see
