### ISSUE TITLE
undefined method 'key?' for nil:NilClass

### ISSUE THREAD

**Issue by genreil** [prawnpdf/prawn#770]
Hi!

The code below throws the following error:
NoMethodError: undefined method `key?' for nil:NilClass
from /home/gen/.rvm/gems/ruby-2.1.2/gems/ttfunk-1.2.2/lib/ttfunk/table/glyf.rb:30:in`for'

The code:
def generate_pdf(file_name)
  pdf = Prawn::Document.new
  pdf.font("#{Rails.root}/app/assets/fonts/myriad-pro.ttf") # the font is there for sure
  pdf.text "Hello, World!"
  pdf.render_file(file_name)
end

I have also tried to add the font with:
  pdf.font_families.update('MyriadPro' => {:normal => "#{Rails.root}/app/assets/fonts/myriad-pro.ttf"})
  pdf.font("MyriadPro")

It was giving the same error.

Of course without the line "pdf.font("#{Rails.root}/app/assets/fonts/myriad-pro.ttf")" everything works just fine.

I can't see what could be possibly wrong in that line, so I suspect that it is an issue with prawn or ttfunk.

Thanks!

**Comment by donwea** [comment]
I have the same issues with another font, HelveticaNeueLTStd-Bd 97 black condensed, but with HelveticaNeueLTStd-Bd i dont have any problem

**Comment by netzc** [comment]
I had the same problem as OP and used the [subsetting tool](https://everythingfonts.com/subsetter) from the site that @practicingruby mentioned to create a subset of the (corrupt?) ttf file I wanted to use with prawn. 
I can use the subset ttf file without an problems.
An on workaround for me, until I get around to diving into how fonts really work, like @mojavelinux suggests.

**Comment by jnicho02** [comment]
I dug into the code, and copies of MyriadPro.ttf on the web have missing 'glyf' and 'loca' records in their table. ttfunk correctly throws an error (although it could be a little more helpful about doing so). Regenerating with fontforge or similar is probably the only way to fix it. I don't believe that ttfunk can guess very easily.
