### ISSUE TITLE
Include full font descriptors for all AFM fonts

### ISSUE THREAD

**Issue by bradediger** [prawnpdf/prawn#81]
Beginning in PDF 1.5, the special treatment afforded the Base 14 AFM fonts is deprecated; producers are supposed to include full font descriptors for every font used.

**Comment by pointlessone** [comment]
Adobe doesn't provide any of "standard PDF fonts" for free. There are a few  knock-offs on the internet but source of those fonts is unclear and licensing is questionable. Also they all are inferior to Adobe fonts (or paid fonts of other foundries).

We can drop special treatment for standard fonts and let users specify fonts they have installed on their system but I don't think it's beneficial for our users. It adds friction and requires more actions to produce a basic document. It somewhat heightens entry barrier.

---

I will close this issue now. Feel free to reopen if you have anything to move forward the conversation.

**Comment by gettalong** [comment]
@pointlessone You could do something like I do for HexaPDF, see https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/font/type1_wrapper.rb#L149, i.e. using what's available in the AFM files and providing default values for the rest.

**Comment by pointlessone** [comment]
Is there a practical difference since PDF 1.7 is still backwards compatible and renderers are expected to handle default fonts.

**Comment by gettalong** [comment]
No, I don't think that there is a practical difference. It's just a bit better to follow the spec to be on the safe side.
