### ISSUE TITLE
Image quality degrades in PDF

### ISSUE THREAD

**Issue by atstockland** [prawnpdf/prawn#811]
Im not sure if it is anti-aliasing or compression...but, PNG images I place in prawn pdf's are really fuzzy.  I use the height and width settings to ensure the image is not being resized....but, still.  I don't see anything defined in the manual for controlling anti-aliasing or compression for images.  Is there anything I can do to control this?  It seems prawn should just place the image, without altering it.  Perhaps Prawn isn't targeting the image...but, the entire generated PDF has compression.

**Comment by sandal** [comment]
Prawn does not alter the image data, but you can have rendering issues in viewers for various reasons, and there can be DPI-related conversion issues. See the discussion on this thread:

https://groups.google.com/d/msg/prawn-ruby/MbMsCx862iY/6ImCsvLGfVcJ
