### ISSUE TITLE
How to put \n in text

### ISSUE THREAD

**Issue by OpakAlex** [prawnpdf/prawn#813]
Hello!

We have problem with \n and text, see small example:
```ruby
        bounding_box [element.posX.mm, change_position_y(page, element.posY)], width: element.width.mm, height:  element.height.mm do
          formatted_text [text: format_content(element.textContent)]
          stroke_bounds
        end
```

And see what we have: http://monosnap.com/image/8keHKNIRZWN1xmCfxuBMZ4hIybkPdB

**Comment by OpakAlex** [comment]
http://monosnap.com/image/LGjn9v2prLf8WAlpTzmUyxcMBn6k0H

**Comment by sandal** [comment]
Please provide a runnable example that does not rely on your application code.

**Comment by OpakAlex** [comment]
@sandal hi!

why i see in pdf '\n' ?

```
 bounding_box [100, 50], width: 100, height:  80 do
     text 'one two \n one two \n hello'
     stroke_bounds
 end
```

**Comment by sandal** [comment]
@OpakAlex You're using single quotes, which means your string contains a slash followed by an n, not a linefeed character. Try using double quotes instead, i.e. `"one two \n one two \n hello".

**Comment by OpakAlex** [comment]
@sandal, same result, i try(
It's very strange(

**Comment by sandal** [comment]
Sorry, I'm not about to reproduce. Please show your entire script.

**Comment by OpakAlex** [comment]
@sandal, yes. 
Works when use "" instead of ''.

Thanks!
