### ISSUE TITLE
add text to existing pdf

### ISSUE THREAD

**Issue by sokrate** [prawnpdf/prawn#816]
Hello, I'm tried to add text to pdf document but without any success. Used next code:

file = "/root/template.pdf"

Prawn::Document.generate("output.pdf", :template => "/root/template.pdf") do
  text "This is a text in a copied pdf.", :align => :center
end

Anybody can help me with editing of existing document?

**Comment by packetmonkey** [comment]
Support for templates was removed in prawn 0.13.0, the way it was implemented was fundamentally flawed. You can either use an older version of prawn if your use case is simple enough to not run into the myriad of bugs, or you would probably be better suited to use another tool

The old template code was extracted into the [prawn-templates](https://github.com/prawnpdf/prawn-templates) gem but it's unmaintained.

**Comment by sokrate** [comment]
But using last version have any option to add text to existing document?

**Comment by sandal** [comment]
@sokrate: No, sorry. This is currently an unsolved (and very complicated) problem for Prawn.
