### ISSUE TITLE
Possible template removal message

### ISSUE THREAD

**Issue by packetmonkey** [prawnpdf/prawn#817]
We still occasionally get users unaware of the removal of templates running into problems with templates on newer versions of prawn. I propose adding an exception that gets thrown if a user tries to use templates. We could point them to the information on the extraction with the recommendation on downgrading or using a different tool.

I suspect this would help lower support costs.

What does everyone think?

**Comment by sandal** [comment]
We actually did raise a warning for a while before extracting them. If someone is upgrading from 0.12.0 where templates still worked to 1.3 (or 2.0+ as of the next release), They Are Going To Have A Bad Time, no matter what.

**Comment by sandal** [comment]
Something that might help the problem indirectly would be to turn `Prawn.debug` on by default in 2.0.0+, which would raise an error if any key Prawn doesn't support is provided, including `:template`.

**Comment by practicingruby** [comment]
Closing this for now. If we keep seeing confusion around this issue, we can consider re-opening in the future.
