### ISSUE TITLE
Render blob images on prawn document

### ISSUE THREAD

**Issue by marcagas** [prawnpdf/prawn#823]
Hi Guys,

I was working on a system that uses prawn with reference to a40418b0a5ea5f7524444f0d1967d9b3ff18d712 patch. But I decided to install the latest prawn version and tried out the system, the rendering of blob image in pdf is no longer working. 

Here's the code: 
blob = Base64.decode64(signature)
img = Magick::Image.from_blob(blob)[0]

image signature

This raises an error: "can't convert Magick::Image into String". But currently this code is working in production, but after the upgrade it no longer worked. Has anyone encountered this bug already? I tried doing the suggested post in here but it also did not work. http://stackoverflow.com/questions/13769539/is-it-possible-to-render-blob-images-in-a-prawn-document

Best Regards,
marc

**Comment by sandal** [comment]
Please show a full, runnable code sample and then we'll re-open.
