### ISSUE TITLE
Nest background options inside another hash.

### ISSUE THREAD

**Issue by andreiglingeanu** [prawnpdf/prawn#824]
Hello,

In one of my projects I needed a way to configure background image. For example I wanted to give background a position other than [``bounds.top_left``](https://github.com/prawnpdf/prawn/blob/master/lib/prawn/document.rb#L276).

It would be nice if the new options would be nested inside another hash, like this:

```ruby
Prawn::Document.generate("test.pdf",
  background: {
    image: "path/to/image",
    size: {x: 100, y: 100},
    position: {x: 10, y: 10}
    scale: 2
  },
) do
  text "Hello World!"
end
```

We could check if options[:background] is a hash and only in this case introduce new functionallity, just for backward compatibility.

What do you think?

**Comment by sandal** [comment]
For right now I'm trying to avoid expanding the API for things that already have an alternative, even if the alternative isn't ideal.

Once we restore `on_page_create()` (which will be done in 2.0.0, and existed in all releases except 1.3.0), you could use an `image()` call with that to get the same result.
