### ISSUE TITLE
Possible changelog convention

### ISSUE THREAD

**Issue by packetmonkey** [prawnpdf/prawn#826]
@practicingruby Now that we have a change log file, do you have any thoughts on using the http://keepachangelog.com convention? I've been using it on my other projects and I find it easy to read over for important details when doing an upgrade.

Just throwing it out there for discussion.

**Comment by practicingruby** [comment]
Can you open a pull request that demonstrates what our CHANGELOG.md file would look like if we followed this convention? That would help me see to what extent it'll be helpful to us.

**Comment by pointlessone** [comment]
WE use exactly that format in some of our gems but we settled on a little bit different format in Prawn. It still highlight all meaningful changes.
