### ISSUE TITLE
number_pages font antialiasing

### ISSUE THREAD

**Issue by HudsonAfonso** [prawnpdf/prawn#828]
I'm in trouble in the number_pages of my pdf, the text does not have the same treatment as the rest of the file...
![number_pages font antialiasing](https://raw.githubusercontent.com/HudsonAfonso/test/master/CapturFiles_48.png)

**Comment by practicingruby** [comment]
Please provide a runnable code sample that illustrates your problem, and then we'll re-open.

**Comment by HudsonAfonso** [comment]
thank you for your help
