### ISSUE TITLE
Hindi fonts not rendered correctly 

### ISSUE THREAD

**Issue by adhsharad** [prawnpdf/prawn#830]
Hi, 

Why is Prawn rendering hindi fonts incorrectly? We have tried with half a dozen of different hidni fonts like akshar, siddhanta, mangal etc. 

Below is the example of incorrect rendering. The font used here in example is called akshar.
![image](https://cloud.githubusercontent.com/assets/6502615/6389706/25b23374-bdaf-11e4-9ce2-7f9c33082ac7.png)

If rendered correctly it should be like this शीर्षक. Compare the second letter. 

Is there any solution to this problem?

BR Sharad

(Runnable code sample -- added by @practicingruby):

``` ruby
Prawn::Document.generate("x.pdf") do
  font "#{Prawn::DATADIR}/fonts/siddhanta.ttf"
  text "शीर्षक"
end
```

Font is from http://svayambhava.blogspot.fi/p/siddhanta-devanagariunicode-open-type.html

**Comment by practicingruby** [comment]
Please provide a runnable code sample (as well as a download link to a TTF font we can use) and we'll re-open for futher investigation.

**Comment by adhsharad** [comment]
Hi,

We can reproduce the situation by using fallback_fonts.rb from manual.

file = "#{Prawn::DATADIR}/fonts/siddhanta.ttf"
font_families["Siddhanta"] = {
 :normal => { :file => file, :font => "Siddhanta" }
}
file = "#{Prawn::DATADIR}/fonts/Panic+Sans.dfont"
font_families["Panic Sans"] = {
 :normal => { :file => file, :font => "PanicSans" },
}
font("Panic Sans") do
 text("When fallback fonts are included, each glyph will be rendered " +
 "using the first font that includes the glyph, starting with the " +
 "current font and then moving through the fallback fonts from left " +
 "to right." +
 "\n\n" +
 "hello ƒ हेल्लो\n दर्शन ƒ goodbye",
 :fallback_fonts => ["Times-Roman", "Siddhanta"])
end
move_down 20
formatted_text([ { :text => "Fallback fonts can even override" },
 { :text => "fragment fonts (विद्यार्थीहरूको)", :font => "Times-Roman" },
 ],
 :fallback_fonts => ["Times-Roman", "Siddhanta"])


You can download the siddhanta.ttf font from here,

http://svayambhava.blogspot.fi/p/siddhanta-devanagariunicode-open-type.html


The problem is half letters get rendered differently and incorrectly in
prawn.

BR
Sharad

**Comment by practicingruby** [comment]
I'm able to reproduce the problem, but have no idea where to start with figuring out what's wrong, or how to fix it, because I'm unfamiliar with the correct rules for processing Hindi text.

Initially I thought this might be a problem with "combining characters" (for example combining accents and the letter they cover", but I was able to produce the correct output for something like this:

```ruby
Prawn::Document.generate("x.pdf") do
  font "#{Prawn::DATADIR}/fonts/DejaVuSans.ttf"
  text "re\u0301sume\u0301"
end
```

Please provide additional background information on how Hindi text/font processing is supposed to work, even if it's just links to other resources. Right now I just don't know where to start in the troubleshooting process.

**Comment by adhsharad** [comment]
Hi, 

It might be a help to understand the logic behind Hindi fonts.

http://www.microsoft.com/typography/OpenTypeDev/devanagari/intro.htm

BR Sharad

**Comment by practicingruby** [comment]
Thanks. Because it's unlikely that I'll work on this myself in the near future, please feel free to research further and start working on a patch if you get a chance.

**Comment by Pomax** [comment]
Does Prawn use its own shaping engine?

**Comment by Manoj51** [comment]
@practicingruby how does prawn handle conjuncts in other languages?. Does prawn process GSUB/GPOS tables to render the font correctly?.

**Comment by sarojkh** [comment]
@adhsharad Did you get it work? I too have stumbled on this problem with no apparent solution despite searching around and trying out things.

**Comment by awadhwana** [comment]
What is the status of this issue  ? @practicingruby 
 Did you find any fix ? @adhsharad

**Comment by neerajkumarjarvis** [comment]
does anyone solve this issue?

**Comment by sushmitabajgain7** [comment]
Hi, anyone resolved this issue? I am having same issue with **Devnagari fonts** .

We have tried with a different Nepali fonts like **mangal, kalimati, Nirmala** etc.

### The font used here in example is called `mangal`.

```
Prawn::Document.generate("test.pdf") do
  font "#{Prawn::DATADIR}/fonts/mangal.ttf"
  text "कम्पनिको रजिष्टर्ड कार्यालय स्थापना गर्ने सन्दर्भमा"
end

```
Output:

> 
![image](https://user-images.githubusercontent.com/39997265/200749426-750fde47-60a2-45e4-8239-977c0e118e02.png)
