### ISSUE TITLE
Provide option for offset/indentation of first line in text box

### ISSUE THREAD

**Issue by paulmenzel** [prawnpdf/prawn#832]
In contrast to the option `:indent_paragraphs`, it’d be great if there was an option that would just indent the first line of the *whole* text, so that a text box can be added to float around something. If `×××××××××` is already in the background image and the text should float around it.

    ××××××××× Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
    incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
    exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
    in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
    occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

**Comment by practicingruby** [comment]
I think what you're looking for here is a nice way to float text around an image (or some other box). This is something we should have better support for, although I'm not sure whether it belongs in Prawn or in an extension gem.

The proposed solution seems too specific though: There's nothing special about the "first line" of text that wouldn't also apply to the "First N lines" of text. So, while I think there's room for improvement, we might want to come up with a more general solution here.
