### ISSUE TITLE
Add means to find out if text was truncated

### ISSUE THREAD

**Issue by paulmenzel** [prawnpdf/prawn#833]
Is there a way to find out (without visual inspection) if a certain text would get truncated in a text box with the option `:overflow` set to `:truncate`? If not, could a method for that use case be provided?

**Comment by practicingruby** [comment]
Yes, there is a way to do this:

```ruby
Prawn::Document.generate("test.pdf") do
  box = Prawn::Text::Box.new("Truncate this", :width => 50, :height => 20, :document => self)

  overflow = box.render(:dry_run => true)
  
  p box.everything_printed?
  p overflow

  # you can call render(), or create a new box here.
end
```

**Comment by practicingruby** [comment]
A documentation patch would be welcome, as this is a common question!
