### ISSUE TITLE
invalid byte sequence in UTF-8 when use mb_chars

### ISSUE THREAD

**Issue by kaluznyo** [prawnpdf/prawn#837]
Since prawn 2.0, use .mb_chars prawn document raise invalid byte sequence in UTF-8 error.
I use the method mb_chars to upcase accentuate chars 

"générales".mb_chars.upcase => "GÉNÉRALES"
 
I use ruby 2.2.0

Log : 
activesupport (4.1.8) lib/active_support/multibyte/chars.rb:59:in `method_missing'
  prawn (2.0.0) lib/prawn/text/formatted/arranger.rb:82:in `block in format_array='
  prawn (2.0.0) lib/prawn/text/formatted/arranger.rb:81:in `format_array='
  prawn (2.0.0) lib/prawn/text/formatted/wrap.rb:136:in `initialize_wrap'
  prawn (2.0.0) lib/prawn/text/formatted/wrap.rb:48:in `wrap'
  prawn (2.0.0) lib/prawn/text/formatted/box.rb:223:in `block (4 levels) in render'
  prawn (2.0.0) lib/prawn/font.rb:102:in `font_size'
  prawn (2.0.0) lib/prawn/text/formatted/box.rb:216:in `block (3 levels) in render'

**Comment by packetmonkey** [comment]
Can you please include a runnable script for us to reproduce the issue with?

**Comment by kaluznyo** [comment]
pdf = Prawn::Document.new
pdf.text "Hello général World".mb_chars.upcase
pdf.render_file "hello.pdf"

**Comment by practicingruby** [comment]
@kaluznyo: The object returned by `mb_chars` is not a String. Older versions of Prawn may have coincidentally called `to_s` on it, but that was an undefined behavior. If you call `to_s` on your `ActiveSupport::Multibyte::Chars` object, I think you'll get the result you expect.
