### ISSUE TITLE
bounds.bottom and bounds.left return integers when zero

### ISSUE THREAD

**Issue by richardjsimkins** [prawnpdf/prawn#842]
Using the code:
```
Prawn::Document.generate("output.pdf") do
    puts bounds.left
    puts bounds.right
    puts bounds.top
    puts bounds.bottom
end
```
The output will be
```
0
540.0
720.0
0
```
Implying `bounds.bottom` and `bounds.left` in this case are returning integers while `bounds.right` and `bounds.top` are returning floats.
`puts 0.0` will output `0.0`
I'm guessing that because it's the root bounds that the code is returning a literal `0` rather than a literal `0.0`.

**Comment by practicingruby** [comment]
What practical problem is this causing for you?

**Comment by richardjsimkins** [comment]
None.

**Comment by practicingruby** [comment]
If you want to patch bounding box to use `0.0` as a literal for the sake of consistency, that's fine... submit a pull request if so.

But I don't think this will make any functional difference, so it's really just a matter of internal consistency.
