### ISSUE TITLE
Does prawn support output of PDF/X-1a or X3 compliant PDF's  ?

### ISSUE THREAD

**Issue by IbnSaeed** [prawnpdf/prawn#877]
Does prawn support output of PDF/X-1a or X3 compliant PDF's  ?

here is some information on PDF/X

**PDF/X**
http://en.wikipedia.org/wiki/PDF/X

http://www.prepressure.com/pdf/basics/pdfx-1a

**PDF/A**
http://en.wikipedia.org/wiki/PDF/A

**Comment by packetmonkey** [comment]
Prawn doesn't currently support kicking out anything other than a standard PDF. I would be happy to consider a PR to add support  but that's probably a bit ambitious given the current state of the codebase. I don't believe we currently set the trim box or bleed box on our output PDFs nor do we have anything in place to prevent a user from adding an RGB image for example.

**Comment by fidothe** [comment]
I had to write PDF/X PDFs out with Prawn and it was pretty straightforward, as long as you can control any images you're embedding - they need to be CMYK, and Prawn won't police that for you. I'll try and extract an example of that code into a Gist later on. The main differences between PDF/X and normal PDF are the TrimBox and BleedBox settings you need, plus some extra refs (OutputIntent, and embedding an ICC profile). Verbose, but not super tricky.

**Comment by packetmonkey** [comment]
@fidothe neat! Really looking forward to that Gist. Maybe we can add some API's to make what you had to do more straightforward and possibly documented. I'll re-open this because it looks like there is a chance this can work :)

**Comment by mojavelinux** [comment]
I'll add that we're very interested in this feature for users of Asciidoctor PDF (based on Prawn) and would be willing to help implement and/or test. I'll be following the issue.

**Comment by IbnSaeed** [comment]
Excellent news, @fidothe You have got us all excited. Can you please provide a detailed procedure for both PDF/X and PDF/A, if possible

**Comment by fidothe** [comment]
Here you go, everyone: https://gist.github.com/fidothe/32613b44a5b6588531d9

**Comment by fidothe** [comment]
and for reference here, a collection of links to resources about pdf/x-the-format: https://pinboard.in/u:fidothe/t:pdfx

**Comment by packetmonkey** [comment]
Thanks @fidothe !

I'm going to go ahead and re-close this issue as we don't natively support this still. However I think there is opportunity to implement a lot of what @fidothe did as native API's making doing similar work much easier.

There are some easier wins such as adding built in support for setting the trim and bleed boxes, OutputIntent's and allowing the overriding of the version strings. 

I would be interested to hear from you @fidothe on what would have made this easier. There could possibly be a Prawn::PDFX/PDFA in the future.
