### ISSUE TITLE
Possible high memory usage with high-res images

### ISSUE THREAD

**Issue by henrik** [prawnpdf/prawn#880]
We're on an earlier version of Prawn, 1.0.0.rc1, and I'm afraid I'm not in a position to dig into this much further right now, but I'm still reporting it in case someone else wants to try to reproduce it:

We had severe site issues related to memory rising or leaking, and there are indications that it might be related to a *very* high res (38949 * 6666 px) but not very heavy (1.3 MB) image being included in a PDF essentially like below. The image: https://dl.dropboxusercontent.com/u/546793/super_highres_for_prawn_issue.png

Including the nasty open-uri stuff because it seems that it, or it together with Prawn, could be involved in the issue.

``` ruby
require "open-uri"
url = "http://example.com/image.jpg"
the_image = open(url) { |f| f.read }
image the_image, fit: [200, 34], at: [0, y]
```

**Comment by joakimk** [comment]
This caused our rails processes to grow from about 500mb to 20-30 GB.

**Comment by nathansamson** [comment]
Unless i miscalculated this image will take 8gb in data (uncompressed,
32bits per pixel).

So while i cant explain 20gb usage, and prawn might try to do a better job
in reading in chunks this sounds like a not so unexpectedly behavior.

My advise is to scale the image down before it enters prawn. Alternatively
try to recreate the image (if it suits it) as vector which also should
reduce memory consumption (although I am not sure prawn actually supports
something like svg)

Nathan
Op 27 mei 2015 09:35 schreef "Joakim Kolsjö" <notifications@github.com>:

**Comment by henrik** [comment]
@nathansamson Thank you. Yeah, we were just discussing it and realized that the uncompressed bitmap had got to be pretty huge.

Our quickfix was to just scale it down, and I suspect our longer-term fix will be something similar as well.

**Comment by joakimk** [comment]
I guess the 20GB could come from copying the memory at some point, or the way ruby represents the bits in the VM.

**Comment by joakimk** [comment]
I don't know if there is anything prawn could do. I guess it could raise an error if it gets passed a very large image, but by then it's already loaded into memory so it probably won't help.

**Comment by henrik** [comment]
That makes sense. I'll close this issue.

**Comment by packetmonkey** [comment]
@henrik @joakimk You may want to check out the prawn-gmagick gem I wrote, it won't avoid loading the image content into memory but I do the pixel extraction in a C ruby extension using graphicsmagick that may help your render execute faster and with less overhead, but still quite a bit at this size.

I use it to load multiple 100+ MB files into PDFs without too much trouble on other projects so it may help you out here.

**Comment by henrik** [comment]
@packetmonkey Thank you! We'll have a look.
