### ISSUE TITLE
Method to remove page

### ISSUE THREAD

**Issue by andre1810** [prawnpdf/prawn#886]
Is there a method to remove a page?

Best regards
André

**Comment by packetmonkey** [comment]
Not currently,  [PDF::Core:: DocumentState](https://github.com/prawnpdf/pdf-core/blob/master/lib/pdf/core/document_state.rb) implements [#insert_page](https://github.com/prawnpdf/pdf-core/blob/master/lib/pdf/core/document_state.rb#L49-L53) which is called from [Prawn::Document#start_new_page](https://github.com/prawnpdf/prawn/blob/master/lib/prawn/document.rb#L231-L286) calls but nothing to do the reverse.

I'm curious, what is your use case for removing a page you would have added previously?

**Comment by mojavelinux** [comment]
I ran into this same problem. When implementing a document generator, sometimes you get into a situation where you advance to the next page in anticipation of more content, but you then reach the end of file. Sometimes you don't have the proper context to check if more content is coming, so you end up with a blank page at the end of the document.

I quickly hacked something together to remove a trailing blank page. It's rather ugly, but it works.

```ruby
# if we are at the page top after adding all content, it's a blank page
if at_page_top?
# ...or check for the seed value, which is length 2
#if page.dictionary.data[:Contents].stream.length == 2
  pdf_store = state.store
  pdf_objs = pdf_store.instance_variable_get :@objects
  pdf_ids = pdf_store.instance_variable_get :@identifiers
  page_id = pdf_store.object_id_for_page page_number
  contents_id = page.dictionary.data[:Contents].identifier
  pdf_objs.delete page_id
  pdf_objs.delete contents_id
  pdf_ids.delete page_id
  pdf_ids.delete contents_id
  pdf_store.pages.data[:Kids].pop
  pdf_store.pages.data[:Count] -= 1
  state.pages.pop
end
```

I'd love to see a way to do this with a single method call.

**Comment by mojavelinux** [comment]
I'd also like to see a method to check if a page is blank. Basically, did anything get added to it after it was created. As you can see from this code, it's hard to find that out currently.

```ruby
puts 'blank' if page.dictionary.data[:Contents].stream.length == 2
```

**Comment by mojavelinux** [comment]
Btw, the seed value, `q\n`, is added here:

https://github.com/prawnpdf/pdf-core/blob/master/lib/pdf/core/page.rb#L166

**Comment by shevegen** [comment]
I can not speak for the use case of anyone, but I believe for symmetry, it would be nice to be able to remove pages too, simply because it is also possible to add them.

I have not needed it myself yet, but I am auto-generating documentation from a html page (I handle the HTML generation and parsing on my own; once it is finished, I delegate it to prawn), and perhaps I may decide to add or remove pages lateron; I could probably filter prior to sending to prawn too, fair enough, but I may also just happily get rid of some pages like "take out page 11-25, but keep the last page, and the first ten"

**Comment by shevegen** [comment]
> I'd also like to see a method to check if a page is blank.

Perhaps a method called .blank? could be added? Unsure whether it conflicts with anything else, I am not very familiar with the prawn codebase (yet).

**Comment by mojavelinux** [comment]
There's a method on Page from PDF::Core called `imported_page?` to check if the page is was imported from another document. To be parallel, the method for checking for a blank page should be `blank_page?`. Also, it probably belongs in PDF::Core rather than Prawn.

**Comment by mojavelinux** [comment]
> I have not needed it myself yet

From my experience with Prawn, I'd wager that you're going to need it sooner rather than later. I keep needing it...hence why I created a (rather ugly) helper to get it done.

**Comment by sly18** [comment]
I also needed to remove page and I think the problem I encountered might concern other people :

my templates consists of blocks that are dynamically generated, but everything must fit in one page.
Hence, I generate the page multiple times and shrink content or expand it if necessary and I end up removing the unnecessary pages.

I'm doing it with combine pdf but I'd rather stay in house with prawn and avoid multiplying the gems.

Summary -> how would one adapt content to fit page size if not by trying to render and removing pages in excess ?

pardon my english.

**Comment by mojavelinux** [comment]
We have this same challenge in Asciidoctor PDF. What we do is create a scratch document (created by marshaling and unmarshaling the the Prawn::Document), then write into the scratch document to determine the rendered size of a block, then we go back to the main document and write it again knowing how it is going to get laid out.

See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/prawn_ext/extensions.rb#L718-L736.

**Comment by sly18** [comment]
I like the way you hacked it, it must be faster than my way, since I try many times until I get the page I want. If you still want to remove a page :

```ruby
	require "prawn"
    require "combine_pdf"

	def show
        fiche=Fich.find(params[:id])
        pages_that_will_be_destroyed=[]
#Create a new empty pdf with prawn
#Somwhere I have a Class PdfGenerator< Prawn::Document vv
        temp_pdf = PdfGenerator.new(:page_size => 'A4',:margin => 20)
#Get an array of all the pages that need to be destroyed
#une_fiche is a method that will generate the page using the params fiche
        pages_that_will_be_destroyed = temp_pdf.une_fiche(fiche)
#Use combine PDF to remove all the pages I don't need in reverse order
        pdf = CombinePDF.parse temp_pdf.render
        pages_that_will_be_destroyed.reverse.each do |numero_page|
            pdf.remove(numero_page-1)
        end
        send_data pdf.to_pdf, filename: fiche.titre+'.pdf', type: 'application/pdf'
    end
```

**Comment by nielspetersen** [comment]
This issue is part of the current issue (13th) of the RubyIssues. https://rubyissues.ongoodbits.com/. :gem:

**Comment by shevegen** [comment]
I settled for pdftk; its syntax is awful and not a lot of fun...

dfockler on IRC made me aware of the thread here again. :)

To delete page 12 in pdftk you have to use something WEIRD like:

  pdftk in.pdf cat 1-11 13-end output output_file.pdf

Thankfully I can use ruby to help me delete a specific page
using pdftk.

But it would be so much nicer to have this doable via prawn instead.

**Comment by mojavelinux** [comment]
Unfortunately, pdftk isn't being packaged anymore for Fedora/RHEL. As an alternative, you can use python-pyPdf. http://pybrary.net/pyPdf/

**Comment by practicingruby** [comment]
It'd be nice to support this feature, however the entire architecture of Prawn is based on mutable, write-only, one-way rendering of documents. For this reason, unless we can be absolutely certain that a delete call will remove all traces, it'll likely lead to corruption issues in some form or another.

I wouldn't be completely against a patch for this, but the real fix is to rework our underplumbing, which is a pretty big undertaking.
