### ISSUE TITLE
Could you release 2.0.2? 

### ISSUE THREAD

**Issue by claudiofullscreen** [prawnpdf/prawn#888]
Thanks for your amazing job with this gem! :heart: :heart: :heart: :heart: :heart: 

I stumbled upon #801 in my project and I found out that the issue is fixed on `master`.

Since your README says:

> The prawn team will release a new version of prawn every 6 weeks containing any new features and bug fixes that have been completed during the previous release cycle. 

I was wondering if you are planning on releasing 2.0.2 anytime soon. Thanks! :ribbon:

**Comment by packetmonkey** [comment]
The release policy was merged in #846 which started the 6 week timer which ends on June 19th so I currently plan on cutting a release that weekend.

Hope that helps!

**Comment by claudiofullscreen** [comment]
Perfect! Thanks :grin:

On Wed, Jun 3, 2015 at 11:58 AM, Evan Sharp <notifications@github.com>
wrote:

> Closed #888 <https://github.com/prawnpdf/prawn/issues/888>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/prawnpdf/prawn/issues/888#event-321697532>.
>



-- 


 Claudio Baccigalupo  | Software Writer  |  Fullscreen, Inc.
<http://Fullscreen.net>  |  +1.310.202.3333
