### ISSUE TITLE
OTF

### ISSUE THREAD

**Issue by Superpencil** [prawnpdf/prawn#893]
We are trying to create something to support it in Prawn since our entire business depends on it.

CJK fonts like Google's Noto are released solely in OTF for this reason:

> There are currently no plans to release TrueType versions of the Noto Sans CJK 
fonts. One huge advantage of the OpenType/CFF versions is that they have 
superior hinting.

> One issue for TrueType versions that you may not have considered is that **no one 
wants to manual hint nearly a half-million glyphs**. What compounds that issue is 
that the number of people on this planet who are genuinely skilled at manually 
hinting TrueType glyphs may be countable by only one or two hands, and the 
sheer amount of time that the process would take.

Since we use Prawn for thousands of shipping receipts a day, and we now opened the Korean and Japanese markets, this will be an issue, our engineers are looking into it.

**Comment by packetmonkey** [comment]
@Superpencil Cool! Prawn currently supports TTF fonts using our ttfunk library, if you develop an OTF library it would be a big win to add support for that into prawn. We probably will want to end up adding some extension points into the prawn font handling code so you (or anyone else in the future) can add the font support needed.

I'm going to go ahead and close this issue. Feel free to open a pull request with any changes you think need to be made to prawn to support your efforts and we can work though it.

Good luck!

**Comment by mojavelinux** [comment]
This is great news! The Asciidoctor community is very interested in OTF support for the exact same reasons. I intend to follow progress on OTF support closely and help out however I can (as time permits).

@Superpencil I'd recommend that you create another repository, something like otfunk or prawn-otf where you publish the early versions and I'll try to get users from the Asciidoctor community to try it out and give feedback. Once it's functional, I'm sure we can sort out what needs to change in Prawn to integrate it. Probably just an extra clause in the case statement in the Font class (e.g., `when 'otf'`).

**Comment by camertron** [comment]
@mojavelinux @packetmonkey see: https://github.com/prawnpdf/ttfunk/issues/53

**Comment by Superpencil** [comment]
There is a ttf version of Noto CJK available now, so sadly for prawn we went with that ✌🏻

**Comment by gettalong** [comment]
OTF may have support for superior hinting but this alone won't help in case of PDF libraries because with PDF the authoring software, not the rendering software, has to typeset each and every glyph (character).

**Comment by MilanCancarevic** [comment]
@Superpencil can you please let me know where i can find ttf version of NotoSans CJK?
In the end, can Prawn support OTF?

**Comment by Superpencil** [comment]
@MilanCancarevic Unsure where the links are, maybe someone just converted it?

**Comment by MilanCancarevic** [comment]
@Superpencil 
i have found NotoSansCJK TC only in TTF. But i have found a nice replacement for anyone needing CJK font for Prawn: https://github.com/be5invis/source-han-sans-ttf/releases
