### ISSUE TITLE
[Support] Compatible PDF versions

### ISSUE THREAD

**Issue by abelsromero** [prawnpdf/prawn#899]
Hi,

I have a doubt regarding the supported PDF versions and how to set them.
I run a couple of examples and saw that PDFs are generated (according to metadata) following the 1.3 version standard. However, the manual is build with 1.4.

Here is a screenshot of the manual's metadata (note: spanish reader, the second proeprty is the version)
![captura](https://cloud.githubusercontent.com/assets/5781153/9121207/32b912da-3c81-11e5-9ffc-0bcf8d272ba1.PNG)

So, the thing is _is it possible to set prawn to generate the PDF in 1.4 format o higher?_ I mention this, because this is an important requirement to be compliant with PDF/A so the documents can be used in legal processing.

**Comment by cheba** [comment]
Prawn tries to set a minimum version for the document depending on used features. It starts with 1.3. Once a feature that has been introduced in a later version of PDF spec (e.g. 1.4) the version is bumped up accordingly.

You can bump up the version yourself:
```ruby
document.renderer.min_version(1.4)
```

**Comment by abelsromero** [comment]
Thanks. Perfectly answered.

**Comment by abelsromero** [comment]
Sorry, one last question, any plans for version 1.5? I guess this is a long shot, but curious if it's being considered.

**Comment by mojavelinux** [comment]
I believe that question is related to https://github.com/prawnpdf/prawn/issues/877

**Comment by cheba** [comment]
@abelsromero We already have some features that bump document version up to `1.6`. Also PDF is backwards compatible format so you can manually bump up to `1.7` even while your document uses only `1.3` or `1.4` features.

Do you have in mind any `1.5` features that Prawn doesn't support yet?

**Comment by abelsromero** [comment]
> I believe that question is related to #877

Exactly what I was looking for, thanks.

> Do you have in mind any 1.5 features that Prawn doesn't support yet?

Not any in particular, just PDF/A compliance. The basic idea behind PDF/A is creating secure PDF documents that can be read after a long period of time (e.g. 5-10 years) and whose integrity can be certified. Basically, PDF 1.5 is "supposed" to be 100% compatible and version 1.4 depends on how you build the document, the first thing you learn is to embed fonts.
Still, from experience, you must always validate the documents cause you never how it was created.

Let me clarify why I was asking:
In my line of work I have to deal with this requeriment from time to time and I have always relied on propietary software for conversion/generation. So, I was interested in knowing if I prawn could be used as a free alterntive for PDF generation, for instance, using Asciidoctor documents as templates.
For some organitzation (especially public organism like goverments) it is _absolutely_ mandatory to ensure that documents are PDF/A. If not, as work arround, some particular regulations allow to store PDFs for preservation as long as they're signed digitally. That way you can ensure that no one altered the document.

Btw, I run some tests with [PDFBox](https://pdfbox.apache.org/) and I could validate the following points:
* I could sign a prawn generated PDF with keys generated with openssl and keytool, which are the de defacto standards. :+1: 
* I could not validate if a generated document was PDF/A. I am concerned about this not because it did not validate, but because PDFBox just crashed with an exception, which may indicate that some part of the document is not well build. I'll try to reach Apache to see if this an issue of the API.

Also, I found this nice summary of PDF/A features: http://wiki.opf-labs.org/display/REQ/PDF+to+PDF-A+Conversion+Pre-Processor

**Comment by packetmonkey** [comment]
I have used http://www.pdf-tools.com/pdf/validate-pdfa-online.aspx in the past to try and work though corrupt PDF problems, it has been able to handle Prawn PDFs before. I haven't paid to much attention to PDF/A incapability as it wasn't my use case, but I am open to fixes to make sure we can generate PDF/A compliant files.

**Comment by mojavelinux** [comment]
Thanks for providing that detailed information @abelsromero!

As far as I understand from past conversations, Prawn does not yet generate PDF/A documents. However, #877 (and a few other issues) link to prototypes of code that needs to be added to Prawn to achieve this. I'm in favor of Prawn being able to generate PDF/A documents for the reasons you have cited. This is not a requirement that is going to go away and it should be addressed by the core processor (not necessarily an add-on). I'm confused why the issue keeps getting closed because we should be working towards a solution.

**Comment by abelsromero** [comment]
Don't mean to reawaken this thread, just reporting that after 1 week...no answer from the request I send to mailing list of Apache.

**Comment by IbnSaeed** [comment]
Is there a reason for this ticket to be closed ?

**Comment by abelsromero** [comment]
> Is there a reason for this ticket to be closed ?

But maybe we should create a new one being more explicit about PDF/A compliance.

**Comment by packetmonkey** [comment]
I am open to any PRs that would help bring Prawn into PDF/A compliance
