### ISSUE TITLE
Prawn Truck Factor

### ISSUE THREAD

**Issue by gavelino** [prawnpdf/prawn#900]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Prawn** and obtained a value of **2**.

The developers responsible for this TF are:

Felipe Doria - author of 44% of the files
Gregory Brown - author of 32% of the files

To validate our results, we would like to ask **Prawn** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Prawn**?

(b) Do you agree that **Prawn** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Prawn** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by cheba** [comment]
Thank you for detailed report. I don't think Prawn would be in a lot of trouble. Here's why.

We provide commit right to anybody who had their PR merged. This means that there's a lot of people who can continue maintaining the project even after some people stepped down. For example, Gregory was an active maintainer for a while but now he's busy with something else. Evan Sharp does most of the maintenance at the moment and the project is as solid as it ever was. Those two people do not contribute to the project but it's still being maintained and developed.

PS: I guess, this is not an issue. I'll close it. If you still think this is something Prawn community should take an action about feel free to reopen.
