### ISSUE TITLE
Memory used at Require time

### ISSUE THREAD

**Issue by janraasch** [prawnpdf/prawn#906]
Hi there,

running [derailed](https://github.com/schneems/derailed_benchmarks) `bundle:mem` on our Rails 4.2 (`ruby 2.2.3`) app using `prawn v2.0.2` we see that `prawn` is using `22.9102 MiB`:

```bash
prawn: 22.9102 MiB
      ttfunk/subset_collection: 5.0313 MiB
        set: 0.5508 MiB
      pdf/core: 0.9844 MiB
        stringio: 0.3242 MiB
      stringio: 0.5469 MiB
      ttfunk: 0.5117 MiB
      forwardable: 0.5078 MiB
      pdf/core/text: 0.4609 MiB
      digest/sha1: 0.4492 MiB
      digest/md5: 0.4414 MiB
      pathname: 0.4219 MiB
      enumerator: 0.4141 MiB
      pdf/core/byte_string: 0.4063 MiB
      zlib: 0.3984 MiB
      thread: 0.3477 MiB
```

which seems like quiet a lot. Do you think there might be things which can be removed from the bundle? 

I hope you do not mind me bugging you about this. Thank you for this great gem.

**Comment by packetmonkey** [comment]
Most of those are required for the various features we provide, and I'm not sure how we would get away from them. If you dive into it feel free to make a suggestion we can look over, but at first glance I'm not sure what we could do. 

Thanks for the comment, and it's no bother :) We want this to be as fast and efficient as possible!
