### ISSUE TITLE
Prawn only returns PDFs of the size 8.27in by 11.7in

### ISSUE THREAD

**Issue by tysontate** [prawnpdf/prawn#907]
I'm using prawn 2.0.1 with Rails. In my controller I have:

```
respond_to do |format|
  format.pdf do
    render :pdf => 'receipt.pdf'
  end
end
```

And in the view (`receipt.pdf.prawn`), I have:

```
prawn_document do |pdf|
end
```

This returns a PDF with some unusual dimensions:

![screen shot 2015-09-09 at 7 52 49 pm](https://cloud.githubusercontent.com/assets/111501/9779030/6517dac0-572c-11e5-81e0-1ffc78a22785.png)

Specifying `:page_size => "LETTER"` returns the same results, as does `:page_size => "LETTER"`

Is this a known issue?

**Comment by gettalong** [comment]
The size you are getting is of the A4 format but I can't say why.

**Comment by tysontate** [comment]
Ah ha — I was unknowingly using prawn-rails. Passing `:page_size => "LETTER"` to `prawn_document` works.
