### ISSUE TITLE
Writing into a bounding box changes cursor position outside. 

### ISSUE THREAD

**Issue by buggle** [prawnpdf/prawn#908]
When I use a bounding box block, e.g. `canvas`, the cursor position after the block will depend on wether I am writing something within the bounding box block (aka alter the cursor). 

As long as I don't, everything is fine. If I do, the new cursor position will remain inside the bounding box even after the  block. 

Example code: 
```
  # somewhere in the middle of a page with a margin on all sides
    text cursor.to_s   # =>   574.152
    canvas do
      text_box "Text Box leaves cursor unchanged"
    end
    text cursor.to_s  # =>   574.152, writes at the expected position within the text flow. 

    canvas do
      text "Text changes cursor"
    end
    text cursor.to_s # => 754.302, writes unexpectedly within the canvas bounding box, i.e. top left of the page, and appends all following content outside the page margins.
```
Even though code and comments in Prawn::Document suggest that it is intentional,
I'd consider this behaviour counter-intuitive to the best but actual I'd think of this as a bug. What do you think?

**Comment by packetmonkey** [comment]
Thanks for the comment! Where would you have expected the cursor to end up after having written in the box?

**Comment by buggle** [comment]
At `574.152`, i.e. just where it has been before the bounding_box / canvas.

**Comment by packetmonkey** [comment]
So the `#text` method internally ends up creating a Text::Formatted::Box and moving the cursor down, where  calling text_box directly does nothing with the cursor.

Given how text is supposed to be a higher level convenience method, I think I'm ok with this behavior and if you want more precise control, you can instantiate a text_box yourself, as you already discovered. I would be open to a documentation patch that would explain the behavior so people in the future don't run into the same confusion you did.

Thanks!
