### ISSUE TITLE
Saving PDF to cloud storage (eg: S3) without saving anything locally

### ISSUE THREAD

**Issue by chadwtaylor** [prawnpdf/prawn#911]
Looked high and low and not much documentation/example/guidance in this regard:

I am aware I could do this `pdf.render_file("foo.pdf")` and then load and upload the `foo.pdf` file to Amazon S3. 

Is there a way to skip saving the file locally and go straight to saving it to Amazon S3?

Any tips are greatly appreciated.

**Comment by mojavelinux** [comment]
You can save the PDF to a stream using the following call:

https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/converter.rb#L2043-L2045

I had to add a small hack to STDOUT since Prawn tries to call the length method. That's what the extra require does.

**Comment by packetmonkey** [comment]
`Prawn::Document#render` will return the raw PDF stream, `#render_file` just writes that stream to a file on disk.

You should be abel to take the return value from `#render` and send it to whatever library you are using to writing to S3.

**Comment by mojavelinux** [comment]
That's true, though I still think we should fix the issue somehow that you can't pass in a STDOUT object because of the call to length. Should we file a separate issue for that?

**Comment by packetmonkey** [comment]
@mojavelinux Sure that way we can be super clear about the specific use case you have

**Comment by mojavelinux** [comment]
Turns out this is an issue in PDF core (ultimately). I'll file an issue there.

**Comment by mojavelinux** [comment]
Filed as https://github.com/prawnpdf/pdf-core/issues/20
