### ISSUE TITLE
The image :fit option, aligns top-left, can I make it align center?

### ISSUE THREAD

**Issue by Siyfion** [prawnpdf/prawn#912]
```ruby
pdf.image 'image_to_insert.png', :fit => [200, 200]
```

If the image is wider than it is tall, ie. 400 x 200, it will align the image to the top of the "fit" box. Conversely, if the image is taller than it is wide, i.e 200 x 400 it will align the image to the left hand edge of the "fit" box.

Is there anyway I can get access to the image's raw width & height or make it center it instead?

**Comment by packetmonkey** [comment]
`Prawn::Document#image` returns the `Prawn::Images::Image` (or an object that inherits from that) that got added, which does have a `#width` and `#height` method on them.

That API isn't public or really considered stable, but that's one way to get what you want without looking at the file yourself using something like imagemagick.

**Comment by Siyfion** [comment]
@packetmonkey Is it not possible that a `:center` option could be added, or alignment options to the existing `:fit` code?

**Comment by packetmonkey** [comment]
Looking at [#image_position](https://github.com/prawnpdf/prawn/blob/master/lib/prawn/images.rb#L147-L175) you may be able to use the `:position` and `:vposition` options to get the behavior you want.

```ruby
  pdf.image 'img', fit: [200, 200], position: :center, position: :center
````

**Comment by Siyfion** [comment]
@packetmonkey I've ended up doing it with a bit of gmagick wizardry, but good to know... I may well give it a go next time I revisit the code.

**Comment by ruinunes** [comment]
https://github.com/prawnpdf/prawn/issues/912#issuecomment-158663717 does work.
The image needs to be the only element inside its container for correct vertical and horizontal alignment.

**Comment by dorianmariefr** [comment]
for me `pdf.image 'img', position: :center` was enough
