### ISSUE TITLE
TIF support

### ISSUE THREAD

**Issue by mfitzp** [prawnpdf/prawn#915]
I am using [asciidoctor](https://github.com/asciidoctor/asciidoctor) to generate PDFs from asciidoc source (asciidoctor uses Prawn as the PDF generation backend). For the PDF generation I was wanting to embed high-resolution TIF files (vs. PNG for the HTML output).

However, when attempting to embed TIFs I get an error (from Prawn) that  `WARNING: could not embed image: image file is an unrecognised format`, and I noticed on the homepage that only PNG/JPG are listed.

Would it be possible to add TIF (or EPS?) image support to Prawn?

For background see [this asciidoctor issue](https://github.com/asciidoctor/asciidoctor/issues/1513).

**Comment by packetmonkey** [comment]
Currently Prawn only supports PNG and JPG files natively. We have a general rule for only having pure ruby dependencies we control. If you wanted to implement a tiff handler I would be more than happy to review the PR and get it merged in.

In the mean time you may want to check out my [prawn-gmagick](https://github.com/packetmonkey/prawn-gmagick) gem which will add support to prawn for whatever formats your install of graphicsmagick has. In my case I use it to load tiff images into PDFs.

Hope that helps!

**Comment by mfitzp** [comment]
Understood @packetmonkey and thanks for the link to prawn-gmagick will take a look.

**Comment by mojavelinux** [comment]
I didn't know about prawn-gmagick either. Thanks for the tip, @packetmonkey!
