### ISSUE TITLE
text wrapped in bounding box wont auto break to new page

### ISSUE THREAD

**Issue by dnasseri** [prawnpdf/prawn#916]
The following code will produce a one page PDF. The text gets pushed off the bounds of the page instead of breaking onto a new page.

```
require "prawn"

Prawn::Document.generate("repro_1.pdf") do
  100.times do
    bounding_box([0, cursor], width: bounds.right, height: 20) do
      text 'test'
    end
  end
end
```

![screen shot 2015-10-16 at 2 46 41 pm](https://cloud.githubusercontent.com/assets/8558194/10550401/bcf50baa-7414-11e5-9f80-c71ccd8bb0b9.png)

I was under the impression that text should be breaking to a new page. Is this a known issue or intended behaviour?

Interestingly if I don't specify the height of the bounding box, the PDF generated is 50 pages long!
But still the text doesn't actually break to a new page, it just renders a bunch of empty pages.
```
require "prawn"

Prawn::Document.generate("repro_2.pdf") do
  100.times do
    bounding_box([0, cursor], width: bounds.right) do
      text 'test'
    end
  end
end
```

**Comment by iamjohnford** [comment]
I'm not sure if that's the intended behavior with `bounding_box` but you can use `span` if you want the text to automatically break between pages:

```
Prawn::Document.generate("span.pdf") do
  span(bounds.width) do
    100.times do
      text 'test'
    end
  end
end
```

**Comment by dnasseri** [comment]
@iamjohnford thanks for the help, I ended up going with a different approach but this is very useful knowledge to have. I would be interested in helping to create a PR to have the bounding box auto break to a new page if we decide that is what the behavior should be.

**Comment by packetmonkey** [comment]
I'm not sure if having a bounding box implicitly cross pages feels right. Initially (to me at least) the bounding box is a single 'object' that we would place on a page, but I can probably be convinced otherwise with some good use cases, in which case I would then be open to the PR.

**Comment by dnasseri** [comment]
Fair enough. I managed to find a cleaner way to implement what I was looking for using prawn-table. Thanks for the help and such a great gem!

**Comment by padualima** [comment]
@dnasseri bro, you could have shared it here. I want to do it with three columns and I don't know how to do it
