### ISSUE TITLE
Color ignored

### ISSUE THREAD

**Issue by escobera** [prawnpdf/prawn#918]
I have the following code:

```ruby
    @doc.font "#{ASSETS_DIR}/fonts/NeutraTextTF/NeutraTextTF-Book.ttf"
    @doc.font_size 17
    @doc.default_leading 4
    @doc.draw_text  "#text_string", at: [160.mm, 180.mm], color: "c4151c"
```

The ```color``` option on the last line is being ignore and it is being printed in black.

If I go and use
```
@doc.fill_color "c4151c"
```

before the draw_text call it prints correctly.

According to the docs the color option should work. Am I doing something wrong here?

**Comment by iamjohnford** [comment]
Which documentation shows `draw_text` accepts the color option? Here's the API documentation: [#draw_text-instance_method](http://prawnpdf.org/api-docs/2.0/Prawn/Text.html#draw_text-instance_method)

Maybe you're thinking of [#text](http://prawnpdf.org/api-docs/2.0/Prawn/Text.html#text-instance_method) which does accept `color` as a parameter?

If you add `Prawn.debug = true` warnings will appear if you call `draw_text` with unsupported options.

**Comment by escobera** [comment]
Thank you very much, you are completely right I thought text/draw_text/text_box accepted color, but I was mistaken.
