### ISSUE TITLE
bad url on S3

### ISSUE THREAD

**Issue by imidsac** [prawnpdf/prawn#935]
ArgumentError (/app/publichttps://sahel-services.s3.amazonaws.com/options/avatars/1/original/maiga.png not found)

**Comment by cheba** [comment]
@imidsac Could you please expand a bit? What goes wrong? What was you expecting? How can we reproduce the issue?

**Comment by imidsac** [comment]
I upload a picture on S3. I want to get the pdf file with this image. give this error. 
ArgumentError (/app/publichttps://sahel-services.s3.amazonaws.com/options/avatars/1/original/maiga.png not found)

**Comment by imidsac** [comment]
def header(title=nil)
    if @option.avatar?
      logo = "#{@option.avatar.path(:original)}"
      image logo, width: 520, height: 150, :position => :center #pour portrait A4
    else
      logo = "#{Rails.root}/app/assets/images/malinuse.jpg"
      image logo, width: 520, height: 150, :position => :center #pour portrait A4
    end

    if title
      text title, size: 14, style: :bold_italic, align: :center
    end
  end

**Comment by cheba** [comment]
`@option.avatar.path(:original)` must be an `IO` instance or a path to a local file. In your case it seem to be an URL. Prawn doesn't support that. You need to figure out a way to either get an `IO` instance out of your `@options.avatar` object or download and pass a path to the local copy.

**Comment by imidsac** [comment]
I'm really beginner, can you just help me?

**Comment by cheba** [comment]
I'm sorry, I can not. I have no idea what your `@option.avatar` is.

I assume, you're using Rails and some sort of plugin for file uploads. Consult the gem's documentation.

I'm closing this issue as it's not a Prawn error.
