### ISSUE TITLE
PDF Form and AcroForm attributes 

### ISSUE THREAD

**Issue by jobygoude** [prawnpdf/prawn#941]
Hi,

How can we extract AcroForm attributes list to fill PDF ?

In v1.0.0.rc2 release we have access to Acroform attributes but after the first major release these data are missing.

Can you help me ?

**Comment by packetmonkey** [comment]
Some code was pulled out of prawn because it was inherently flawed and we couldn't maintain it.

Can you share some code that used to work that no longer does so I can better understand what isn't working for you anymore please? 

Thanks.

**Comment by jobygoude** [comment]
I would extract AcroForm attributes of Pdf-Form to fill with text or image.
