### ISSUE TITLE
Adopt a code of conduct?

### ISSUE THREAD

**Issue by practicingruby** [prawnpdf/prawn#943]
The only reason I've not done this myself yet is because I'm no longer actively involved in maintenance, and so would not be able to actively monitor for conduct issues in the project.

(However, I *do* have a Code of Conduct for my private community projects, and generally support the idea of having one)

I'm going to lock this issue as soon as I post it, because these things do not generate insightful discussion most of the time. That said, my recommendation would be to adopt the contributor covenant, because it's fairly standard across projects and having a common code does help make it easier for people to understand what to expect:

http://contributor-covenant.org/

Here's what I'd like to see (as former lead maintainer of this project)... at least one person on the maintenance team (current or former) step up to agree to handle conduct-related reports and deal with them appropriately.

Does anyone here want to volunteer here?

@prawnpdf/maintainers @prawnpdf/previous-maintainers 

I would do it myself but I'm 100% committed to other work currently, and so I'm afraid I wouldn't be able to give this the attention it deserves.

(please only comment if you plan to volunteer to do this work, and then from there, let's get the README updated and the code of conduct added, and set up an appropriate email address. I can possibly set up an email forwarding mechanism for conduct@prawnpdf.org if need be)

**Comment by cheba** [comment]
I'm willing to monitor all our official communication channels for signs of breach.

**Comment by practicingruby** [comment]
I discussed with @cheba privately, and I'm actually fairly confident that as long as we have active eyes on the discussion channels, I can help with enforcement.

So I'll get the relevant documentation merged, a communication channel set up, and I'll be there to help whenever we have problems. I am counting on others to be on the look out for issues, but as long as we have someone doing that, we'll be able to make this change.

**Comment by practicingruby** [comment]
@cheba, @packetmonkey: The conduct@prawnpdf.org email is set up, forwarding to all three of us.

Can one of you add the conduct file for contributor covenant + update README?

**Comment by packetmonkey** [comment]
All set.
