### ISSUE TITLE
Rendering text as outline/shape/path

### ISSUE THREAD

**Issue by elsurudo** [prawnpdf/prawn#950]
Let's say I'm using a custom font, but only for a few characters. Or my print shop doesn't support custom embedded fonts, and swaps them out for the fonts available on the old printer (sigh...)

It would be nice to have an option to render text as vector shapes instead, which the printer _does_ know how to handle.

I suppose this could be an additional [text rendering mode](http://www.rubydoc.info/github/sandal/prawn/Prawn%2FCore%2FText%3Atext_rendering_mode). Thoughts?

Or is this already possible somehow?

**Comment by practicingruby** [comment]
Sorry, I don't even know whether this is feasible and we don't track feature requests, only work-in-progress and bug reports.

**Comment by elsurudo** [comment]
Ok. In case anyone else is interested, I used Ghostscript as a post-processing step with the following command as a workaround:

`gs -o output.pdf -dNoOutputFonts -sDEVICE=pdfwrite input.pdf`
