### ISSUE TITLE
Ability to destroy the last or a specific page

### ISSUE THREAD

**Issue by sobrinho** [prawnpdf/prawn#958]
I'm not sure if it's a good idea but would be nice to be able to destroy a page for situations like this:

``` ruby
things.each do |thing|
  # do some rendering

  document.start_new_page
end
```

If you do not want an empty page on the document, you need to perform some check, like this:

``` ruby
things.each do |thing|
  # do some rendering

  if thing != things.last
    document.start_new_page
  end
end
```

If you can destroy a page, you could avoid the check in every iteration, like this:

``` ruby
things.each do |thing|
  # do some rendering

  document.start_new_page
end

document.destroy_last_page
```

Do you think that's too strange or does it makes sense?

**Comment by andre1810** [comment]
For me it makes sense and I would recommend it.
