### ISSUE TITLE
ActionController::UnknownFormat error

### ISSUE THREAD

**Issue by atchyut-re** [prawnpdf/prawn#959]
Installed Gem and created pdf.prawn view. When I am accessing url with .pdf. Its giving me ActionController::UnknownFormat Do I need to register the Mime type again ?

**Comment by pointlessone** [comment]
No, in most cases Rails can pick up the MIME-type. However, you may use constructions like this in your controller:
```ruby
respond_to do |format|
  format.html
end
```

In that case you need to explicitly handle `pdf` format in the controller.

**Comment by straydogstudio** [comment]
Prawn does not provide a `.prawn` template handler for Rails, even though the MIME type is registered. That means you can't put the code in a template and have it work. You'd have to do everything in the controller, or in some model.

But you can look at [prawn-rails](https://github.com/cortiz/prawn-rails).

**Comment by cgrepo** [comment]
define it on contig/mime_types.rb
  Mime::Type.register "application/pdf", :pdf

**Comment by cgrepo** [comment]
first u need to register the mime type in 
config/initializers/mime_types.rb
  Mime::Type.register "application/pdf", :pdf

**Comment by Vish-was** [comment]
getting `ActionController::UnknownFormat`

**ActionController::UnknownFormat (ActionController::UnknownFormat):**

on 

> respond_to do |format|
>       format.pdf do
>         render :pdf => "file_name"   # Excluding ".pdf" extension.
>       end
>     end

**Comment by pointlessone** [comment]
@Vish-was See previous comment.
