### ISSUE TITLE
Usage of html_safe attribute in Prawn PDF syntax

### ISSUE THREAD

**Issue by atchyut-re** [prawnpdf/prawn#960]
I'm rendering the PDF data from the output of CK editor (What you see is what you get editor).
The output from that editor would be included with all the HTML, CSS tags in the content. For that I had used 'html_safe' attribute in the show page. But when I try to use the same attribute in the PDF prawn syntax its not working. Can someone please guide me how to get the pure content without all the HTML tags in Prawn PDF.

Thanks in advance.

**Comment by pointlessone** [comment]
`html_safe` is a part of ActionView, not Prawn. You would need to use some other library to clean up your strings. I believe, `html_safe` doesn't remove any markup from string but escapes it on unsafe strings. To achieve similar effect you can use `cgi` library from Ruby stdlib. For instance: `CGI.escape_html(unsafe_string)`.

If you want to just keep text and remove all markup I don't think there's anything in stdlib for that. You would have to look at gems like [loofah](https://rubygems.org/gems/loofah).

**Comment by atchyut-re** [comment]
After a long a Google search I finally got an answer which I wish to share with you.

As html_safe is the action view method in rails, It can not be used in ruby syntax of Prawn pdf.

So for that we can use:

`ActionView::Base.full_sanitizer.sanitize(@string)
`

[http://api.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html#method-i-strip_tags](http://api.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html#method-i-strip_tags)
