### ISSUE TITLE
Document#start_new_page shouldn't mutate its options

### ISSUE THREAD

**Issue by johncip** [prawnpdf/prawn#962]
We started freezing constants recently [to satisfy Rubocop](http://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Style/MutableConstant).

Our usage is similar to:

```ruby 
class ReportRenderer
  MARGINS = { margin: 54.0, bottom_margin: 72.0 }.freeze

  def initialize
    @pdf = Prawn::Document.new(MARGINS)
    # ...
  end

  def add_contents
    @pdf.start_new_page(MARGINS) # RuntimeError: can't modify frozen Hash
    # ...
  end
end
```

(In reality, we set the margins on each new page because sometimes we change them for a particular page based on its content, but a class constant seems like the right place to put the default ones.)

In any case, mutating an option hash seems to violate principle of least surprise (at least, we were surprised when our PDFs broke 😄 ) and the fix is straightforward enough.

The modification happens here, in `apply_margin_options`:
https://github.com/prawnpdf/prawn/blob/master/lib/prawn/document.rb#L693

This can serve as a test case:

```
Prawn::Document.new.start_new_page({margin: 0}.freeze)
```

**Comment by johncip** [comment]
Hey @crazymykl -- made a PR here, if it helps: https://github.com/prawnpdf/prawn/pull/963

**Comment by johncip** [comment]
Hey, when's the appropriate time to close these? After the PR makes it in, or after the next release?

**Comment by pointlessone** [comment]
@johncip Don't worry about that. We do issue triage once in a while and clean up these resolved issues.
