### ISSUE TITLE
Multiple tests fails

### ISSUE THREAD

**Issue by Fale** [prawnpdf/prawn#967]
Hello,

I'm starting to work on prawn for Fedora and I've noticed that a lot of tests fails:

https://kojipkgs.fedoraproject.org//work/tasks/8414/14508414/build.log

Is there a known reason for this? Should I be worry?

**Comment by packetmonkey** [comment]
I'm not currently aware of what would cause the failure, given how [our CI](https://travis-ci.org/prawnpdf/prawn) is currently green, I'm inclined to think it's related to whatever redhat did to package prawn.

I'm going to go ahead and close this issue but feel free to follow-up if you have more information.

Thanks for letting us know!
