### ISSUE TITLE
Prawn::Font::AFM.hide_m17n_warning = true doesn't seem to work

### ISSUE THREAD

**Issue by amyxguo** [prawnpdf/prawn#968]
Hi, 

I would like to disable this warning, and have characters show up (corrupted if needed) when rendering the pdf. I set Prawn::Font::AFM.hide_m17n_warning = true in the initialize function of an instance of Prawn::Document class. Still, after setting the flag, I get the error message when some characters are not supported. http://take.ms/5V4Hf

```
class NewItineraryPdf < Prawn::Document
  def initialize(itinerary,itinerary_view_model,current_user_view_model)
    super()
    Prawn::Font::AFM.hide_m17n_warning = true
    mona = "#{Rails.root}/public#{ActionController::Base.helpers.asset_url('mona.ttf')}"

    font_families.update(
      "mona" => {
        :normal      => { :file => mona, :font => "Mona" },
        :italic      => mona,
        :bold        => mona,
        :bold_italic => mona
    })
    @itinerary = itinerary
    @itinerary_view_model = itinerary_view_model
    @current_user_view_model = current_user_view_model
    test_text
  end
  
def fallback_fonts
    ["mona"]
 end

def test_text
      text "漢字 foo"
  end
end

```

**Comment by pointlessone** [comment]
Hello @amyxguo,

As far as I can tell, that flag only disable the warning for built in fonts. Since you are using a custom font that flag doesn't work. Also you are not getting a warning. You are getting an exception which means that your font lacks glyphs for your text.

Recommended solution would be to add another font that definitely contains full set of glyphs you may need and use it as a fallback.

As for your desired solution, it is against our goals to produce corrupted documents so we are not going to implement it. However, you may monkey-patch prawn to do that.

I will close the issue now but feel free to reopen if you think the issue can be resolved in another way.

**Comment by amyxguo** [comment]
Hi @pointlessone,

Thanks for your response. Do you have any suggestions on finding a font that contains full set of glyphs I may need other than trial and error? I've tried 3 different Japanese supporting fonts, mona, msmincho, and fireflysung, and none of them covers all the characters I need to display. 

I'm trying to display pdf text version of itineraries - https://gojourny.com/new_itineraries/Z1O and https://gojourny.com/new_itineraries/qzb (without icons, images, maps). The display works for the second itinerary https://gojourny.com/new_itineraries/qzb.pdf?pdf=true, but I've yet found a font that contains all the glyphs needed to display the first itinerary. 

Best,
-Amy

**Comment by jds13** [comment]
Instead of displaying them as glyphs, can you insert what you need as images using the Prawn::Images image method?

**Comment by amyxguo** [comment]
I'm not trying to display images, just texts. Is there a way to find which character is causing the Prawn::Errors::IncompatibleStringEncoding?

**Comment by pointlessone** [comment]
@amyxguo Try these fonts: http://www.wazu.jp/gallery/Fonts_ChineseTraditional.html

The characters in your example look Chinese to me but then Kanji is adopted Chinese characters. I'm not sure if Unicode makes distinction between Kanji and Chinese character, though.

**Comment by jds13** [comment]
The traceback should show the file and line where the error was detected. You can edit that and add a print statement - e.g. (for my setup, one possibility) in C:\Ruby\lib\ruby\gems\2.2.0\gems\prawn-2.1.0\lib\prawn\font\afm.rb, above line 138 insert something like
 `print "Glyph present for #{char} (#{char.ord})\n`
The offending character will be the last line in your log.

**Comment by amyxguo** [comment]
@jds13 That helped me to drill down to the character that's causing the issue. It turned out to be '−'
This is neither '-' or '–'. Does anyone have suggestions on how to find a font that's compatible with '−'?

**Comment by jds13** [comment]
Erm I may be embarassing myself here but I use this function to clean up certain inputs:

```
def FixFunnyChars(m)
   mo = ''
   m.each_byte do |mi|
      case mi
         when 0x91 then mo +='\''   # [Prawn::Encoding::WinAnsi::CHARACTERS.index('quoteleft')].pack("U")
         when 0x92 then mo +='\''   # [Prawn::Encoding::WinAnsi::CHARACTERS.index('quoteright')].pack("U")
         when 0x93 then mo +='"'    # [Prawn::Encoding::WinAnsi::CHARACTERS.index('quotedblleft')].pack("U")
         when 0x94 then mo +='"'    # [Prawn::Encoding::WinAnsi::CHARACTERS.index('quotedblright')].pack("U")
         when 0x96 then mo +='-'    # [Prawn::Encoding::WinAnsi::CHARACTERS.index('endash')].pack("U")
         when 0x97 then mo +='-'    # [Prawn::Encoding::WinAnsi::CHARACTERS.index('emdash')].pack("U")
         when 0x85 then mo +='...'  # [Prawn::Encoding::WinAnsi::CHARACTERS.index('ellipsis')].pack("U")
         when 0xA9 then mo += [Prawn::Encoding::WinAnsi::CHARACTERS.index('copyright')].pack("U")
         when 0xAE then mo += [Prawn::Encoding::WinAnsi::CHARACTERS.index('registered')].pack("U")
         when 0x99 then mo += [Prawn::Encoding::WinAnsi::CHARACTERS.index('trademark')].pack("U")
         when 0x92 then mo += [Prawn::Encoding::WinAnsi::CHARACTERS.index('cent')].pack("U")
         else           mo += mi.chr
         end
      end
   mo
   end
```

**Comment by amyxguo** [comment]
Thanks! I found the character is hyphen minus, and used arial unicode ms to support it!
