### ISSUE TITLE
Support for a built-in digital signature mechanism

### ISSUE THREAD

**Issue by why-el** [prawnpdf/prawn#969]
Hey,

Is there or was there at some point an interest in having a built-in way to electronically sign a document? Currently one must resort to other solutions that operate on finished files but I think it would be great to simply use Prawn objects with some built it niceties like a `sign` method and some good defaults. 

I am not sure how much effort it will be to support all the nitty gritty details of pdf signatures (attached vs detached, what to sign with, should it depend on openssl, and so on).

**Comment by packetmonkey** [comment]
Prawn is mostly for the creation of PDFs where signing I believe is a modification so it probably falls out of scope. With that said if there was an API prawn could provide that would allow an external gem to build that functionality, that could be worth looking into..

Thanks for thinking of prawn!
