### ISSUE TITLE
TrueType fonts are not part of the gem package

### ISSUE THREAD

**Issue by adamniedzielski** [prawnpdf/prawn#970]
We have some TrueType fonts bundled with the gem, living in `data/fonts` directory, for example `DejaVuSans.ttf`. However, they are not added to the package when uploading the files to RubyGems - https://github.com/prawnpdf/prawn/blob/d850baed73a2c75579c9b26a213ea8ee790d46fb/prawn.gemspec#L12 and hence they are not available when downloading the gem from RubyGems server.

Is there anything which prevents us from bundling these fonts in the gem package?

**Comment by pointlessone** [comment]
Hi Adam,

They are only used for tests. The library does not use any of those fonts. Also there are possible issues with font redistribution according to their license. That has not been properly investigated.

**Comment by cdekker** [comment]
Are TrueTypeFonts still supported? I tested with both
```font(Rails.root.join('app/assets/fonts/DejaVuSans.ttf').to_s)```
and the longer font_families.update() method, but I always get the 'Bad font family' exception.

The .ttf file is obviously present at that location, manually downloaded from the git repo.

**Comment by adamniedzielski** [comment]
@cdekker I can confirm that `nimbus-normal.ttf` font works for me with Prawn 2.1.0.

**Comment by matkoniecz** [comment]
From  #1023 

> You should not use fonts from Prawn repo. Most of these fonts have newer versions available. The older versions in the repo are good enough for our purpose — testing.

**Comment by matkoniecz** [comment]
Would you accept PR that removes current .ttf files, adds new ones and enables packaging of .ttf files?

Requirements for new font files that I know about:

- tests are still passing
- clear licensing situation and it is OK to distribute font files
- font files are usable for displaying at least some UTF-8 characters beyond ASCII

Anything else?

**Comment by pointlessone** [comment]
@matkoniecz Thank you but no. We do not intent to distribute fonts. Developers are expected to take care of fonts they want to use in their projects themselves.

---

Than you everyone for discussion. I hope the issue have been cleared up.

I will close this issue now. Feel free to reopen if you have anything constructive to add.
