### ISSUE TITLE
Really, really odd behaviour...?

### ISSUE THREAD

**Issue by Siyfion** [prawnpdf/prawn#972]
I've created a label for print with some text and tables, etc. (Attached)

But there is a load of information at the bottom of the page (which if you try to select, you can see positionally) that simply does not appear at all.

I've opened up the PDF in Acrobat and if I so much as change one little thing, all of it then re-renders correctly (I assume Acrobat is "fixing" the issue on save)...

@practicingruby / @packetmonkey Any idea's would be great! As I'm currently a bit stuck helping a customer until I can understand this better!

[uni309_YAPzvqyWS7Ek5BPFL_20160809-125327.pdf](https://github.com/prawnpdf/prawn/files/408838/uni309_YAPzvqyWS7Ek5BPFL_20160809-125327.pdf)

**Comment by Siyfion** [comment]
And another odd one for you... Using a Google Font, renders some bits fine, others, not...

If you highlight the text, copy & paste it's all there, so it's a rendering / PDF issue rather than a data issue.

[pla005_rXard8Sudm56Fwmhh_20161020-151229.pdf](https://github.com/prawnpdf/prawn/files/542125/pla005_rXard8Sudm56Fwmhh_20161020-151229.pdf)

**Comment by Siyfion** [comment]
@packetmonkey I could really use some help in figuring this out, otherwise I may have to switch away from Prawn, which I *really* don't want to do!

**Comment by pointlessone** [comment]
Prawn does font subsetting as an optimization to keep your documents small. You may want to try and trace if it does it properly with your font. The code is in [TTFunk](https://github.com/prawnpdf/ttfunk) gem. I don't have other ideas at the moment.

**Comment by Siyfion** [comment]
@pointlessone Thanks for the words of wisdom, I'll try to take a look, clearly something's gone nuts.

**Comment by Siyfion** [comment]
@pointlessone As a quick and dirty fix, is there a way to turn subsetting off?!

**Comment by pointlessone** [comment]
@Siyfion I'm afraid, no. IIRC, it's not a removal of unused glyphs but rather import of the used ones. You may hack TTF to include all glyphs, or maybe even just use original font file instead of generating a subset. But I don't think there's a way to just turn subsetting off.

**Comment by Siyfion** [comment]
Damn. Well it's this font: https://fonts.google.com/specimen/Taviraj?selection.family=Taviraj

Is there a way to use font's in a pdf that can be retrieved from a url? Like a CSS import?

**Comment by pointlessone** [comment]
Technically, PDF has means to reference external resources (including via URL). But I'm not sure if this is applicable specifically to fonts. Check out [PDF Reference](https://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf).

**Comment by gettalong** [comment]
@Siyfion It would help if you could provide a small script that reproduces the error. As for external object streams specified via URLs: Yes, this should be possible, see section 7.11.5. However, I doubt that there would be much support for that feature.

**Comment by Siyfion** [comment]
@pointlessone @gettalong Minimal code reproduction done and attached. It's literally hello-world with a font and different character-set.
[test.zip](https://github.com/prawnpdf/prawn/files/550405/test.zip)

**Comment by Siyfion** [comment]
@pointlessone & @gettalong 
Or if people prefer no random zip file:

```ruby
require "prawn"

Prawn::Document.generate("hello.pdf") do
  font("Taviraj/Taviraj-Regular.ttf") do
    text "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890-=!@$%^&*()__+}"
  end
end
```

Outputs the following:

[hello.pdf](https://github.com/prawnpdf/prawn/files/553353/hello.pdf)

**Comment by gettalong** [comment]
@Siyfion I'm not *that* paranoid ;) So thanks for the ZIP-File.

What I can confirm right now is that the embedded font is not a valid TrueType font. When extracting the font stream and opening it with FontForge, it throws errors. However, if we replace the font with another one, like `Roboto-Regular.ttf`, everything works flawlessly.

Also, running `ttfdump -t glyf FILE` on the extracted font stream will give you an error after the second glyph (from 77). I think the problem comes from the Taviraj font using composite glyphs and ttfunk perhaps not properly supporting them but that is only a guess.

What you experience with Acrobat may be that Acrobat re-subsets the font on save and therefore everything works correctly.

**Comment by Siyfion** [comment]
@gettalong If I open the TTF in FontForge, I don't seem to get anything too out of the ordinary..?

**Comment by gettalong** [comment]
@Siyfion Did you open the original TrueType font or the one embedded into the PDF file? The original one works fine but the embedded one is corrupt.

**Comment by Siyfion** [comment]
The original, surely that means that the font file I'm using is perfectly
fine and that it's the way it's being embedded that's at fault?

-- 
Simon Mansfield

**Comment by gettalong** [comment]
@Siyfion Yes, the original file also works correctly for me but not the embedded subset of the file and, as you said, this means that subsetting does not work for this file.

**Comment by Siyfion** [comment]
@gettalong So where does the error lie (in what piece of code?)

**Comment by Siyfion** [comment]
Wow, that's er... waaaay outside my comfort zone to try and debug/fix. Guess I'll have to wait until someone can take a proper look at it.

**Comment by gettalong** [comment]
@Siyfion No problem, I think I will some time today to have a look.

**Comment by gettalong** [comment]
@Siyfion I tracked down the problem after some lengthy investigation (I'm not that familiar with ttfunk myself) and have opened an issue (see https://github.com/prawnpdf/ttfunk/issues/32) where you will also find the fix that you can apply to your ttfunk installation.

**Comment by Siyfion** [comment]
Awesome work! Thank you so much for looking into it!

-- 
Simon Mansfield

**Comment by Siyfion** [comment]
Confirmed that @gettalong's fix does indeed cure this issue. I'd like to get the change merged into the release if possible, as I'm sure this affects more than just one or two fonts!

**Comment by pointlessone** [comment]
This issue is fixed in TTFunk 1.5.1. I will close it now. Feel free to reopen in case it doesn't work for you and you have new details.

@gettalong Thank you for the research you did on this issue.

**Comment by Siyfion** [comment]
@pointlessone & @gettalong, awesome work both of you. 👍

**Comment by swistak** [comment]
For anyone who stumbles upon it and for some reason't can't easily upgrade to new version of prawn a workaround (from master) is:

```ruby
unless Prawn::VERSION > '0.13'
  module TTFunk
    class Table
      class Loca
        # Backport from current master to fix https://github.com/prawnpdf/ttfunk/issues/32
        def self.encode(offsets)
          long_offsets =
            offsets.any? do |offset|
              short_offset = offset / 2
              short_offset * 2 != offset || short_offset > 0xffff
            end

          if long_offsets
            { type: 1, table: offsets.pack('N*') }
          else
            { type: 0, table: offsets.map { |o| o / 2 }.pack('n*') }
          end
        end
      end
    end
  end
```
