### ISSUE TITLE
Overlaping between current ant total pages number in footer

### ISSUE THREAD

**Issue by zenzei** [prawnpdf/prawn#973]
Hi!

I'm using last prawn version and I'm having a strange issue with page numbering. It seems on every page I got an overlapping between the current page and the total pages number.

This is the test code

```
require "prawn"

Prawn::Document.generate("document.pdf", :page_layout => :portrait) do
    start_new_page

    # Footer
    repeat :all do
        bounding_box [bounds.left, bounds.bottom+30], :width  => bounds.width, :height => 30 do
        end

        # Paging
        string = "<page> / <total>"
        options = { :at => [bounds.right - 165, -15],
                    :width => 150,
                    :align => :right,
                    :size => 8,
                    :start_count_at => 1}
        number_pages string, options
    end
end
```

And here the pdf that this code generates [document.pdf](https://github.com/prawnpdf/prawn/files/416573/document.pdf)

I saw a thread in stackoverflow that talks about this http://stackoverflow.com/questions/31019388/solved-using-prawn-gem-on-rails-app-repeating-footer-with-current-page-total, but the canvas solution didn't work for me.

It's there any error in my code, or it's a bug in prawn?
Thanks!

(By the way, despite this small issue prawn is really awesome!)

**Comment by zenzei** [comment]
Sorry for asking again, can you tell me if i'm doing something wrong within my code that produce the overlapping between current and total pages?
Thanks!

**Comment by pointlessone** [comment]
You shouldn't use `number_pages` inside a repeater. It's a handy helper that goes over each page and puts a number on it. You should use it after your document has all pages generated.

Repeater is a more generic solution. It makes sure your block of code is executed after all pages are generated. It can be used to number pages but also for anything else you want to do on each page.

You should use either `repeat :all` or `number_pages` but not `number_pages` inside of `repeat`.

Hope this helps.

---

I will close this issue now. Feel free to reopen if you have anything to add.

**Comment by zenzei** [comment]
Oh that was really easy! I didn't rememeber where I got that example in the past or why I didn't try that before. 

Just for reference, only moving the number_pages outside of the block made it work as expected.
```
require "prawn"

Prawn::Document.generate("document.pdf", :page_layout => :portrait) do
    start_new_page

    # Footer
    repeat :all do
        bounding_box [bounds.left, bounds.bottom+30], :width  => bounds.width, :height => 30 do
        end
    end


    # Paging
    string = "<page> / <total>"
    options = { :at => [bounds.right - 165, -15],
                    :width => 150,
                    :align => :right,
                    :size => 8,
                    :start_count_at => 1}
    number_pages string, options
end
```
Thank you so much @pointlessone!

What do you think about adding a warning in the "number_pages" api doc docs so nobody make that silly mistake like I did?

**Comment by pointlessone** [comment]
It would be nice to have that documented. I would welcome a PR. ;)
