### ISSUE TITLE
CMYK mode not working

### ISSUE THREAD

**Issue by activestylus** [prawnpdf/prawn#981]
I've established my colors with four integer arguments as per the docs

`pdf.fill_color 10,20,30,40`

The PDF gets generated, but the document mode is set to RGB. Im creating a lot of files on the fly, and its tedious to have to open each one in illustrator, change the color mode and resave.

I thought there might be some universal flag to set this parameter but the docs and source code don't seem to provide any answers.

Any clues?

**Comment by gettalong** [comment]
Can you provide a minimal example Ruby script that generates a PDF with the wrong color mode and post it here?

**Comment by activestylus** [comment]
Here's the full script: https://gist.github.com/activestylus/b532b5131f2e31dcf39efdf55135c133

The script accepts three arguments, 

1: Folder/File Name (no spaces)
2: Width
3: Height

It works quite well to generate files on the fly. Hust have no idea how to trigger CMYK Mode

**Comment by activestylus** [comment]
Here is the full script - it's highly customized and depends on certain folder structure which doesn't make it very portable. But perhaps you can see where I went wrong? 

https://gist.github.com/activestylus/b532b5131f2e31dcf39efdf55135c133

**Comment by gettalong** [comment]
Thanks for the script but I don't see any problem in the resulting PDF - Adobe Reader is showing it just fine. Can you also provide your corrected version to find the difference?

**Comment by activestylus** [comment]
Adobe Reader is meant for on screen use so of course RGB is the default. But when you open this file in Illustrator, the color mode is set to RGB, when it should be CMYK, making it useless for print production.

**Comment by gettalong** [comment]
Since access to proprietary software is limited, please help us out by providing some more information. This could be the resaved PDF file you mentioned initially or what you mean by "color mode".

**Comment by activestylus** [comment]
A dont actually use Acrobat. Adobe Illustrator is my workhorse for production. All PDFs are set to a certain colorspace, whether authored in the app or not. I cant speak for how other software does this but see attached screenshot for how Illustrator handles it. 
![image](https://cloud.githubusercontent.com/assets/285/18227307/601e1eb6-7220-11e6-98d5-349590bc068b.png)

**Comment by gettalong** [comment]
Thanks for the color mode explanation!

I have looked at the PDF content stream operators created by your example and they correctly set the /DeviceCMYK color space before setting the color values. I'm not an expert but from what I can see this should be all that needs to be done.

Could you provide a PDF with the color mode changed to CMYK by using Adobe Illustrator? Maybe other values are set within the PDF file to make it appear differently.

Another question: Is there an actual difference when printing out both color versions of the PDF on the same printer?

**Comment by activestylus** [comment]
There is a visual difference in print and even on screen. If you take an RGB PDF and open it in illustrator, then change to CMYK it shifts the whole color space to give an accurate preview. 

![image](https://cloud.githubusercontent.com/assets/285/18280471/6951948c-7459-11e6-82a6-6e0e822701ff.png)

**Comment by activestylus** [comment]
Here are two files, hopefully you can do a diff on them to see if there is any particular flag that needs to be set

[PDF_COLOR_TEST.zip](https://github.com/prawnpdf/prawn/files/457126/PDF_COLOR_TEST.zip)

**Comment by gettalong** [comment]
@activestylus Thanks for the files but they contain vastly different files. To potentially find out the difference I will need the original PDF file and the original file opened in Illustrator and saved with the changed mode.

The two files RGB.pdf and CMYK.pdf look like the RGB example in the left on your pictures, i.e. no subdued colors, like on the right side. I looked at them using Evince on Linux and Reader on Windows.

**Comment by activestylus** [comment]
Try this 
[Archive.zip](https://github.com/prawnpdf/prawn/files/457479/Archive.zip)

**Comment by gettalong** [comment]
Thanks for those, they help!

Alas, I don't think that Prawn can do anything like you want.

The colors used for the CMYK rectangles as well as the RGB rectangles are (in that order):

* For `rgb.pdf` only /DeviceRGB is used, so all the values below have to be interpreted as `R G B`
  * `0 0.678 0.933`
  * `0.922 0 0.545`
  * `1 0.945 0`
  * `0.137 0.122 0.125`
  * `1 0 0`
  * `0 1 0 `
  * `0 0 1`

* For `cmyk.pdf` only /DeviceCMYK is used, so all the values below have to be interpreted as `C M Y K`:
  * `1 0 0 0`
  * `0 1 0 0`
  * `0 0 1 0`
  * `0 0 0 1`
  * `0 0.988 1 0`
  * `0.625 0 1 0`
  * `0.879 0.766 0 0`

As you can see Adobe Illustrator is changing every /DeviceRGB color into a /DeviceCMYK color, probably using an ICC profile that you configured.

So it seems that the color mode change in Illustrator just does that: Changing every color either to /DeviceRGB or /DeviceCMYK. I couldn't find anything else that relates to the change.

Note that inside a PDF (even in one content stream) you can *mix* /DeviceRGB and /DeviceCMYK colors however you want! This is also supported by Prawn. If you specify a CSS color value for a color setter, it is interpreted as a /DeviceRGB color, if you use four values, as a /DeviceCMYK color.

So I don't think that the PDF files that Prawn generates are incorrect. If you want to use CMYK colors, than use CMYK color values in Prawn.

You may also read up on the Illustrator setting to see what it is supposed to do.

**Comment by activestylus** [comment]
Thanks for looking into this so thoroughly. If I find a way to manually tweak the file accordingly so it matches Illustrator's desired mode I will post it here

**Comment by activestylus** [comment]
OK so to follow up I was curious what would happen when I created empty documents and just saved those in different color modes. I may have honed in on the key diff, which allows me to hack together a solution, but I thought you'd like to see the diff in question on line 183:

![image](https://cloud.githubusercontent.com/assets/285/18361349/c93a2a36-7601-11e6-9816-438de1c00b29.png)

Here are the files:
 [Archive 2.zip](https://github.com/prawnpdf/prawn/files/462370/Archive.2.zip)

**Comment by gettalong** [comment]
Thanks for the follow up but what you found has nothing to do with PDF itself. For example, the data you show on the right side of the picture concerning `white-rgb.pdf` is inside the PDF object (53,0), referenced from PDF object (52,) via the key AIMetaData.

These two objects don't belong to PDF itself but to private data embedded by Illustrator. They are useless for any conforming PDF reader because they are not part of the PDF spec. Therefore probably no program except Illustrator will look at the data.

So if you want that conversion to happen automatically, you will need to find out what *exactly* Illustrator does with the colors and manually change the color values and color spaces, which will probably not be so easy.
