### ISSUE TITLE
Validate join_style

### ISSUE THREAD

**Issue by systemed** [prawnpdf/prawn#988]
At present you can pass an unrecognised value to `join_style` and it'll silently break the PDF output, resulting in something that will be opened by some PDF readers (e.g. Apple Preview) but not others (anything by Adobe).

This is a good way of catching out British English speakers like me who might accidentally write `:mitre`!

Ideally Prawn::Graphics::JoinStyle.join_style should throw an exception if anything other than `:miter`, `:round` or `:bevel` is requested.

**Comment by piton4eg** [comment]
@pointlessone I guess it can be closed

**Comment by pointlessone** [comment]
Indeed. Thank you for reminder.
