### ISSUE TITLE
Prawn::Errors::UnsupportedImageType (PNG uses unsupported interlace method)

### ISSUE THREAD

**Issue by isness** [prawnpdf/prawn#992]
I'm getting this error on trying to include interlaced PNG image. Any suggestions on how I could avoid this error? I use paperclip_compression gem to save images with paperclip ("-interlace Plane" argument)

**Comment by pointlessone** [comment]
Hello,

Prawn doesn't support interlaced PNGs natively. We'll gladly accept a PR for this functionality.

Alternatively, you can try [prawn-gmagick](https://github.com/packetmonkey/prawn-gmagick) or convert your images to non-interlaced PNGs in any other way.

I will close this issue now. Feel free to reopen if you have anything to add.

**Comment by shyjanharsha** [comment]
> Are you solve this issue

**Comment by legacy370** [comment]
I had an interlaced image that bombed in Prawn.  To overcome that, I loaded the image into GIMP, then used the option Image -> Merge Visible Layers, then File -> Export As   a png file.

**Comment by Yaqzan** [comment]
Thank you @legacy370 Your solution saved me
