### ISSUE TITLE
handling image urls using the CLI

### ISSUE THREAD

**Issue by DoWhileGeek** [prawnpdf/prawn#998]
I've read around that when using prawn as a module(not sure if thats what they're called, I'm a python guy) you can drop in a method to handle image urls, but that doesn't seem to be the case when using it in the command line, or through `kramdown`. Is there any hope this will become a thing?

**Comment by DoWhileGeek** [comment]
Just realized this should be fixed on the kramdown side, sorry for the intrusion!

**Comment by gettalong** [comment]
@DoWhileGeek No, will probably not be fixed in kramdown's PDF converter since it provides only the basics. If you need more than that you need to subclass the PDF converter and provide the additional functionality, like remote images and so on.

**Comment by DoWhileGeek** [comment]
@gettalong is kramdown open to a PR of this variety?

**Comment by gettalong** [comment]
@DoWhileGeek Sure
