### ISSUE TITLE
Error when zero length is provided to dash array

### ISSUE THREAD

**Issue by Nowass** [prawnpdf/prawn#999]
Hi,
Currently I am dealing with the "zero length" restriction in the dash array (already mentioned in [commit](https://github.com/prawnpdf/prawn/commit/e65c24411c451918718a8e8cb35631c98ccc5517)) cause, that dotted lines can't be rendered from the SVG source.

The PDF spec says [1]: 

> The dash array’s elements are numbers that specify the lengths of alternating dashes and gaps; the numbers must be nonnegative and not all zero.

 my understanding of this specification is that it zero length is not forbidden (as it is implemented right now) if there is another one non-zero. I would say that it depends on which segment length is zero ... for example, a segment defined by [0,2] (ON phase 0 units, OFF phase 2 units) should be still valid. Therefore the check should verify if not all values are zero, and if there are some zeroes in which phases it is.
This is my feeling which is based on how the dashed lines are interpreted by several different software (viso, inkscape, smartDraw, ...) ... but maybe I am wrong ...

P.S. If this if case is commented out, prawn-svg module knows how to handle this kind of line, and the dotted lines are rendered correctly 

----
[1]: PDF Reference 1.7, Section 4.3.2: Details of Graphic State Parameters, Line Dash Pattern

**Comment by practicingruby** [comment]
As this gets worked on, please see this related ticket (especially toward the bottom)

https://github.com/prawnpdf/prawn/issues/497

**Comment by gettalong** [comment]
See pull request #1001 for a fix
